-- INSERT USERS
INSERT INTO CMSY0900A (USER_ID,PASSWORD) VALUES ('hami','1234');

-- INSERT AUTHORITIES
INSERT INTO CMSY0901A (USER_ID, AUTHORITY) VALUES ('hami', 'USER');
INSERT INTO CMSY0901A (USER_ID, AUTHORITY) VALUES ('hami', 'ADMIN');