-- CREATE HRPM0100A 인사마스터
DROP TABLE HRPM0100A CASCADE CONSTRAINTS PURGE;

CREATE TABLE HRPM0100A (
  C_CD                       VARCHAR2(20 BYTE) NOT NULL,
  EMP_ID                     VARCHAR2(20 BYTE) NOT NULL,
  STAT_CD                    VARCHAR2(20 BYTE),
  ENTER_TYPE                 VARCHAR2(20 BYTE),
  BIZPL_CD                   VARCHAR2(20 BYTE),
  RE_GRD_CD                  VARCHAR2(20 BYTE),
  ENTER_YMD                  VARCHAR2(8 BYTE),
  GRP_YMD                    VARCHAR2(8 BYTE),
  RETIRE_YMD                 VARCHAR2(8 BYTE),
  EXPT_PROB_END_YMD          VARCHAR2(8 BYTE),
  ATTEND_STA_YMD             VARCHAR2(8 BYTE),
  RET_STA_YMD                VARCHAR2(8 BYTE),
  LAST_MOVE_YMD              VARCHAR2(8 BYTE),
  LAST_PROM_YMD              VARCHAR2(8 BYTE),
  SAL_STEP_YMD               VARCHAR2(8 BYTE),
  DUTY_APP_YMD               VARCHAR2(8 BYTE),
  NEXT_SAL_STEP_YMD          VARCHAR2(8 BYTE),
  LAST_EMP_TITLE_PROM_YMD    VARCHAR2(8 BYTE),
  PER_NO                     VARCHAR2(200 BYTE),
  OFR_STA_YMD                VARCHAR2(8 BYTE),
  GENDER_TYPE                VARCHAR2(20 BYTE),
  EMP_NM                     VARCHAR2(500 BYTE),
  CHA_EMP_NM                 VARCHAR2(500 BYTE),
  ENG_EMP_NM                 VARCHAR2(500 BYTE),
  BIRTH_YMD                  VARCHAR2(8 BYTE),
  LNS_TYPE                   VARCHAR2(20 BYTE),
  MARRY_YN                   VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (MARRY_YN IN ('N','Y')),
  MARRY_YMD                  VARCHAR2(8 BYTE),
  FAM_ORGN_NM                VARCHAR2(100 BYTE),
  FAM_MASTER_NM              VARCHAR2(100 BYTE),
  FAM_MASTER_RELA_CD         VARCHAR2(20 BYTE),
  RELIGION_CD                VARCHAR2(20 BYTE),
  HOBBY_TXT                  VARCHAR2(100 BYTE),
  SKILL_TXT                  VARCHAR2(100 BYTE),
  BODY_HEIGHT                NUMBER DEFAULT 0 NOT NULL,
  BODY_WT                    NUMBER DEFAULT 0 NOT NULL,
  LEFT_SIGHT_NUM             NUMBER DEFAULT 0 NOT NULL,
  RIGHT_SIGHT_NUM            NUMBER DEFAULT 0 NOT NULL,
  BLOOD_TYPE                 VARCHAR2(20 BYTE),
  COLORSENSE_CD              VARCHAR2(20 BYTE),
  HOUSEHOLD_CD               VARCHAR2(20 BYTE),
  IDTY_SCH_YN                VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (IDTY_SCH_YN IN ('N','Y')),
  NTNL_CD                    VARCHAR2(20 BYTE),
  OFFICE_TEL_NO              VARCHAR2(100 BYTE),
  TEL_NO                     VARCHAR2(100 BYTE),
  EGC_TEL_NO                 VARCHAR2(100 BYTE),
  MOBILE_NO                  VARCHAR2(100 BYTE),
  MAIL_ADDR                  VARCHAR2(100 BYTE),
  HOMEP_ADDR                 VARCHAR2(100 BYTE),
  PHOTO_PATH                 VARCHAR2(100 BYTE),
  BF_EMP_ID                  VARCHAR2(20 BYTE),
  BASEAREA_CD                VARCHAR2(20 BYTE),
  BIRTH_LOC_CD               VARCHAR2(20 BYTE),
  OUT_DISP_ASSO_CD           VARCHAR2(20 BYTE),
  RET_ORG_NM                 VARCHAR2(100 BYTE),
  RET_EMP_GRADE_NM           VARCHAR2(100 BYTE),
  ASSO_EMP_GRADE_NM          VARCHAR2(100 BYTE),
  PSPT_NO                    VARCHAR2(64 BYTE),
  PSPT_END_YMD               VARCHAR2(8 BYTE),
  PSPT_KIND_CD               VARCHAR2(20 BYTE),
  UNION_TYPE                 VARCHAR2(20 BYTE),
  FIRST_EMP_ID               VARCHAR2(20 BYTE),
  RESI_YN                    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (RESI_YN IN ('N','Y')),
  REG_DRT_YN                 VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (REG_DRT_YN IN ('N','Y')),
  RECMD_NM                   VARCHAR2(100 BYTE),
  GRP_TRANS_YMD              VARCHAR2(8 BYTE),
  RET_RSN_CD                 VARCHAR2(20 BYTE),
  RE_TYPE                    VARCHAR2(20 BYTE),
  GRADE_STA_YMD              VARCHAR2(8 BYTE),
  SPC_JG_CD                  VARCHAR2(20 BYTE),
  CAREER_PROM_POINT          NUMBER DEFAULT 0 NOT NULL,
  RE_ORDER_NO                VARCHAR2(20 BYTE),
  LOC_CD                     VARCHAR2(20 BYTE),
  MEDI_NOTE                  VARCHAR2(1000 BYTE),
  OUT_MAIL_ADDR              VARCHAR2(50 BYTE),
  TAX_LOC_CD                 VARCHAR2(20 BYTE),
  EMP_TITLE_STD_YMD          VARCHAR2(8 BYTE),
  PROM_STD_YMD               VARCHAR2(8 BYTE),
  EMP_TYPE_CHG_YMD           VARCHAR2(8 BYTE),
  CEN_RNW_YMD                VARCHAR2(8 BYTE),
  RECMD_RELA_CD              VARCHAR2(20 BYTE),
  PHOTO_YN                   VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (PHOTO_YN IN ('N','Y')),
  SIGN_YN                    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (SIGN_YN IN ('N','Y')),
  BOND_COM_CD                VARCHAR2(20 BYTE),
  BOND_ACC_NO                VARCHAR2(224 BYTE),
  FAX                        VARCHAR2(100 BYTE),
  WORK_PLACE_NM              VARCHAR2(100 BYTE),
  EMP_TYPE                   VARCHAR2(20 BYTE),
  ICB_CLASS_CD               VARCHAR2(20 BYTE),
  WORK_LOC_TEL_NO            VARCHAR2(100 BYTE),
  WORK_LOC_FAX               VARCHAR2(100 BYTE),
  CAREER_FROM_YY             NUMBER DEFAULT 0,
  MPVA_YN                    VARCHAR2(1 BYTE) DEFAULT 'N',
  RETIRE_YN                  VARCHAR2(1 BYTE) DEFAULT 'N',
  EXPT_RETIRE_YMD            VARCHAR2(8 BYTE),
  CAREER_FROM_MM             NUMBER DEFAULT 0,
  CAREER_FROM_DD             NUMBER DEFAULT 0,
  JOB_DESC                   VARCHAR2(500 BYTE),
  EMPCARD_YN                 VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (EMPCARD_YN IN ('N','Y')),
  JOB_CLASS_CD               VARCHAR2(20 BYTE),
  JOB_CLASS_CHG_YMD          VARCHAR2(8 BYTE),
  ORG_ID_STA_YMD             VARCHAR2(8 BYTE),
  WORK_LOC_ID_STA_YMD        VARCHAR2(8 BYTE),
  LAST_APPNT_CD              VARCHAR2(20 BYTE),
  WELFARE_CARD_YN            VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (WELFARE_CARD_YN IN ('N','Y')),
  MESSENGER_NM               VARCHAR2(100 BYTE),
  EXPT_PROB_MON_APPLY_RATE   NUMBER,
  VOIP                       VARCHAR2(100 BYTE),
  FOREIGN_YN                 VARCHAR2(1 BYTE) DEFAULT 'N',
  INS_USER_ID                VARCHAR2(20 BYTE),
  INS_YMDHMS                 DATE,
  MOD_USER_ID                VARCHAR2(20 BYTE),
  MOD_YMDHMS                 DATE
);

COMMENT ON TABLE HRPM0100A IS '인사마스터';

COMMENT ON COLUMN HRPM0100A.C_CD IS '회사코드';

COMMENT ON COLUMN HRPM0100A.EMP_ID IS '사번';

COMMENT ON COLUMN HRPM0100A.STAT_CD IS '재직상태';

COMMENT ON COLUMN HRPM0100A.ENTER_TYPE IS '입사유형';

COMMENT ON COLUMN HRPM0100A.BIZPL_CD IS '사업장코드';

COMMENT ON COLUMN HRPM0100A.RE_GRD_CD IS '채용등급코드';

COMMENT ON COLUMN HRPM0100A.ENTER_YMD IS '입사일';

COMMENT ON COLUMN HRPM0100A.GRP_YMD IS '그룹입사일';

COMMENT ON COLUMN HRPM0100A.RETIRE_YMD IS '퇴사일';

COMMENT ON COLUMN HRPM0100A.EXPT_PROB_END_YMD IS '수습종료일';

COMMENT ON COLUMN HRPM0100A.ATTEND_STA_YMD IS '연차기산일';

COMMENT ON COLUMN HRPM0100A.RET_STA_YMD IS '퇴직금기산일';

COMMENT ON COLUMN HRPM0100A.LAST_MOVE_YMD IS '최종이동일';

COMMENT ON COLUMN HRPM0100A.LAST_PROM_YMD IS '최종승진일';

COMMENT ON COLUMN HRPM0100A.SAL_STEP_YMD IS '최종승급일';

COMMENT ON COLUMN HRPM0100A.DUTY_APP_YMD IS '최종직책변동일';

COMMENT ON COLUMN HRPM0100A.NEXT_SAL_STEP_YMD IS '차기승급일';

COMMENT ON COLUMN HRPM0100A.LAST_EMP_TITLE_PROM_YMD IS '최종직위변동일';

COMMENT ON COLUMN HRPM0100A.PER_NO IS '주민번호';

COMMENT ON COLUMN HRPM0100A.OFR_STA_YMD IS '임원선임일';

COMMENT ON COLUMN HRPM0100A.GENDER_TYPE IS '성별유형';

COMMENT ON COLUMN HRPM0100A.EMP_NM IS '사원명';

COMMENT ON COLUMN HRPM0100A.CHA_EMP_NM IS '한자사원명';

COMMENT ON COLUMN HRPM0100A.ENG_EMP_NM IS '영문사원명';

COMMENT ON COLUMN HRPM0100A.BIRTH_YMD IS '생일';

COMMENT ON COLUMN HRPM0100A.LNS_TYPE IS '음양유형';

COMMENT ON COLUMN HRPM0100A.MARRY_YN IS '결혼여부';

COMMENT ON COLUMN HRPM0100A.MARRY_YMD IS '결혼일';

COMMENT ON COLUMN HRPM0100A.FAM_ORGN_NM IS '본적';

COMMENT ON COLUMN HRPM0100A.FAM_MASTER_NM IS '호주명';

COMMENT ON COLUMN HRPM0100A.FAM_MASTER_RELA_CD IS '호주관계코드';

COMMENT ON COLUMN HRPM0100A.RELIGION_CD IS '종교코드';

COMMENT ON COLUMN HRPM0100A.HOBBY_TXT IS '취미내용';

COMMENT ON COLUMN HRPM0100A.SKILL_TXT IS '특기내용';

COMMENT ON COLUMN HRPM0100A.BODY_HEIGHT IS '신장';

COMMENT ON COLUMN HRPM0100A.BODY_WT IS '체중';

COMMENT ON COLUMN HRPM0100A.LEFT_SIGHT_NUM IS '좌시력NUM';

COMMENT ON COLUMN HRPM0100A.RIGHT_SIGHT_NUM IS '우시력NUM';

COMMENT ON COLUMN HRPM0100A.BLOOD_TYPE IS '혈액형';

COMMENT ON COLUMN HRPM0100A.COLORSENSE_CD IS '색각코드';

COMMENT ON COLUMN HRPM0100A.HOUSEHOLD_CD IS '주거코드';

COMMENT ON COLUMN HRPM0100A.IDTY_SCH_YN IS '신원조회여부';

COMMENT ON COLUMN HRPM0100A.NTNL_CD IS '국가코드';

COMMENT ON COLUMN HRPM0100A.OFFICE_TEL_NO IS '구내전화번호(미사용)';

COMMENT ON COLUMN HRPM0100A.TEL_NO IS '집 전화번호';

COMMENT ON COLUMN HRPM0100A.EGC_TEL_NO IS '비상연락망';

COMMENT ON COLUMN HRPM0100A.MOBILE_NO IS '이동전화';

COMMENT ON COLUMN HRPM0100A.MAIL_ADDR IS '메일주소';

COMMENT ON COLUMN HRPM0100A.HOMEP_ADDR IS '홈페이지주소';

COMMENT ON COLUMN HRPM0100A.PHOTO_PATH IS '사진PATH';

COMMENT ON COLUMN HRPM0100A.BF_EMP_ID IS '이전사번';

COMMENT ON COLUMN HRPM0100A.BASEAREA_CD IS '생활근거지코드';

COMMENT ON COLUMN HRPM0100A.BIRTH_LOC_CD IS '출신지역코드';

COMMENT ON COLUMN HRPM0100A.OUT_DISP_ASSO_CD IS '외부파견기관코드';

COMMENT ON COLUMN HRPM0100A.RET_ORG_NM IS '퇴직소속명';

COMMENT ON COLUMN HRPM0100A.RET_EMP_GRADE_NM IS '퇴직직급명';

COMMENT ON COLUMN HRPM0100A.ASSO_EMP_GRADE_NM IS '외부기관직급명';

COMMENT ON COLUMN HRPM0100A.PSPT_NO IS '여권번호';

COMMENT ON COLUMN HRPM0100A.PSPT_END_YMD IS '여권만료일';

COMMENT ON COLUMN HRPM0100A.PSPT_KIND_CD IS '여권종류코드';

COMMENT ON COLUMN HRPM0100A.UNION_TYPE IS '노조유형';

COMMENT ON COLUMN HRPM0100A.FIRST_EMP_ID IS '최초사번';

COMMENT ON COLUMN HRPM0100A.RESI_YN IS '거주여부';

COMMENT ON COLUMN HRPM0100A.REG_DRT_YN IS '등기이사여부';

COMMENT ON COLUMN HRPM0100A.RECMD_NM IS '추천인명';

COMMENT ON COLUMN HRPM0100A.GRP_TRANS_YMD IS '그룹전입일';

COMMENT ON COLUMN HRPM0100A.RET_RSN_CD IS '퇴직사유코드';

COMMENT ON COLUMN HRPM0100A.RE_TYPE IS '채용유형';

COMMENT ON COLUMN HRPM0100A.GRADE_STA_YMD IS '직급년차기준일';

COMMENT ON COLUMN HRPM0100A.SPC_JG_CD IS '해외인선직군코드';

COMMENT ON COLUMN HRPM0100A.CAREER_PROM_POINT IS '경력승진포인트';

COMMENT ON COLUMN HRPM0100A.RE_ORDER_NO IS '채용기수';

COMMENT ON COLUMN HRPM0100A.LOC_CD IS '지역코드';

COMMENT ON COLUMN HRPM0100A.MEDI_NOTE IS '병력';

COMMENT ON COLUMN HRPM0100A.OUT_MAIL_ADDR IS '외부메일주소';

COMMENT ON COLUMN HRPM0100A.TAX_LOC_CD IS '납세지역코드';

COMMENT ON COLUMN HRPM0100A.EMP_TITLE_STD_YMD IS '호칭기준일';

COMMENT ON COLUMN HRPM0100A.PROM_STD_YMD IS '승진기준일';

COMMENT ON COLUMN HRPM0100A.EMP_TYPE_CHG_YMD IS '직원유형변경일';

COMMENT ON COLUMN HRPM0100A.CEN_RNW_YMD IS '계약갱신일';

COMMENT ON COLUMN HRPM0100A.RECMD_RELA_CD IS '추천인관계코드';

COMMENT ON COLUMN HRPM0100A.PHOTO_YN IS '사진여부';

COMMENT ON COLUMN HRPM0100A.SIGN_YN IS '사인여부';

COMMENT ON COLUMN HRPM0100A.BOND_COM_CD IS '증권회사코드';

COMMENT ON COLUMN HRPM0100A.BOND_ACC_NO IS '증권계좌번호';

COMMENT ON COLUMN HRPM0100A.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN HRPM0100A.INS_YMDHMS IS '입력일시';

COMMENT ON COLUMN HRPM0100A.MOD_USER_ID IS '작업자ID';

COMMENT ON COLUMN HRPM0100A.MOD_YMDHMS IS '수정일시';

COMMENT ON COLUMN HRPM0100A.FAX IS '팩스';

COMMENT ON COLUMN HRPM0100A.WORK_PLACE_NM IS '근무위치';

COMMENT ON COLUMN HRPM0100A.EMP_TYPE IS '사원유형';

COMMENT ON COLUMN HRPM0100A.ICB_CLASS_CD IS '재직구분코드';

COMMENT ON COLUMN HRPM0100A.WORK_LOC_TEL_NO IS '근무지전화';

COMMENT ON COLUMN HRPM0100A.WORK_LOC_FAX IS '근무지FAX';

COMMENT ON COLUMN HRPM0100A.CAREER_FROM_YY IS '경력인정년';

COMMENT ON COLUMN HRPM0100A.MPVA_YN IS '원호대상여부';

COMMENT ON COLUMN HRPM0100A.RETIRE_YN IS '퇴사여부';

COMMENT ON COLUMN HRPM0100A.EXPT_RETIRE_YMD IS '퇴사예정';

COMMENT ON COLUMN HRPM0100A.CAREER_FROM_MM IS '경력인정월';

COMMENT ON COLUMN HRPM0100A.CAREER_FROM_DD IS '경력인정일';

COMMENT ON COLUMN HRPM0100A.JOB_DESC IS '담당업무';

COMMENT ON COLUMN HRPM0100A.EMPCARD_YN IS '사원증발급여부';

COMMENT ON COLUMN HRPM0100A.JOB_CLASS_CD IS '직종코드';

COMMENT ON COLUMN HRPM0100A.JOB_CLASS_CHG_YMD IS '최종직종변동일';

COMMENT ON COLUMN HRPM0100A.ORG_ID_STA_YMD IS '원소속발령시작일';

COMMENT ON COLUMN HRPM0100A.WORK_LOC_ID_STA_YMD IS '근무지발령시작일';

COMMENT ON COLUMN HRPM0100A.LAST_APPNT_CD IS '최종변동구분(발령코드)';

COMMENT ON COLUMN HRPM0100A.WELFARE_CARD_YN IS '복지카드발급여부';

COMMENT ON COLUMN HRPM0100A.MESSENGER_NM IS '메신저주';

COMMENT ON COLUMN HRPM0100A.EXPT_PROB_MON_APPLY_RATE IS '수습임금적용';

COMMENT ON COLUMN HRPM0100A.VOIP IS 'VOIP';

COMMENT ON COLUMN HRPM0100A.FOREIGN_YN IS '외국인여부';

CREATE INDEX IX_HRPM0100A ON
  HRPM0100A (
    C_CD
    ASC,
    PER_NO
    ASC );

CREATE UNIQUE INDEX PK_I_HRPM0100A ON
  HRPM0100A (
    C_CD
    ASC,
    EMP_ID
    ASC );

ALTER TABLE HRPM0100A ADD CONSTRAINT PK_I_HRPM0100A PRIMARY KEY ( C_CD, EMP_ID );

--CREATE TABLE HRPO0100A
DROP TABLE HRPO0100A CASCADE CONSTRAINTS PURGE;

CREATE TABLE HRPO0100A (
  C_CD                  VARCHAR2(20 BYTE) NOT NULL,
  EMP_ID                VARCHAR2(20 BYTE) NOT NULL,
  STA_YMD               VARCHAR2(8 BYTE) NOT NULL,
  SEQ_NO                NUMBER DEFAULT 0 NOT NULL,
  END_YMD               VARCHAR2(8 BYTE),
  DOC_NO                VARCHAR2(20 BYTE),
  APPNT_CD              VARCHAR2(20 BYTE),
  APPNT_RSN_CD          VARCHAR2(20 BYTE),
  STAT_CD               VARCHAR2(20 BYTE),
  BIZPL_CD              VARCHAR2(20 BYTE),
  ORG_ID                VARCHAR2(20 BYTE),
  EMP_TYPE              VARCHAR2(20 BYTE),
  EMP_GRADE_CD          VARCHAR2(20 BYTE),
  SAL_STEP_CD           VARCHAR2(20 BYTE),
  DUTY_CD               VARCHAR2(20 BYTE),
  JOB_ID                VARCHAR2(20 BYTE),
  POST_CD               VARCHAR2(20 BYTE),
  EMP_TITLE_CD          VARCHAR2(20 BYTE),
  POSITION_ID           VARCHAR2(20 BYTE),
  DISP_ORG_ID           VARCHAR2(20 BYTE),
  DISP_DUTY_CD          VARCHAR2(20 BYTE),
  DISP_JOB_ID           VARCHAR2(20 BYTE),
  DISP_POSITION_ID      VARCHAR2(20 BYTE),
  OUT_DISP_ASSO_CD      VARCHAR2(20 BYTE),
  EXPT_PROB_END_YMD     VARCHAR2(8 BYTE),
  EXPT_END_YMD          VARCHAR2(8 BYTE),
  DUTY_APP_YMD          VARCHAR2(8 BYTE),
  APP_GRADE             VARCHAR2(20 BYTE),
  LAST_YN               VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (LAST_YN IN ('N','Y')),
  SAL_TYPE              VARCHAR2(20 BYTE),
  APPLY_YMD             VARCHAR2(8 BYTE),
  PAY_AREA_CD           VARCHAR2(20 BYTE),
  ATTEND_AREA_CD        VARCHAR2(20 BYTE),
  WORK_LOC_ID           VARCHAR2(20 BYTE),
  SCH_END_YMD           VARCHAR2(8 BYTE),
  STAT_CLASS            VARCHAR2(20 BYTE),
  TMP_REST_RSN_CD       VARCHAR2(20 BYTE),
  BTRIP_CLASS           VARCHAR2(20 BYTE),
  NTNL_CD               VARCHAR2(20 BYTE),
  ROT_WORK_YN           VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (ROT_WORK_YN IN ('N','Y')),
  WORK_LOC_ID_LEG       VARCHAR2(20 BYTE),
  ORG_ID_LEG            VARCHAR2(20 BYTE),
  HD_COM_CD             VARCHAR2(20 BYTE),
  APP_EXEC_YN           VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (APP_EXEC_YN IN ('N','Y')),
  APP_EXEC_UPDATE_YN    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (APP_EXEC_UPDATE_YN IN ('N','Y')),
  APP_EXEC_MAIL_YN      VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (APP_EXEC_MAIL_YN IN ('N','Y')),
  SEL_STEP_CD           VARCHAR2(20 BYTE),
  PROB_END_YMD          VARCHAR2(8 BYTE),
  REMARK                VARCHAR2(4000 BYTE),
  ASSIGN_STA_YMD        VARCHAR2(8 BYTE),
  NOTE                  VARCHAR2(4000 BYTE),
  INS_USER_ID           VARCHAR2(20 BYTE),
  INS_YMDHMS            DATE,
  MOD_USER_ID           VARCHAR2(20 BYTE),
  MOD_YMDHMS            DATE
);

COMMENT ON TABLE HRPO0100A IS
  '인사발령';

COMMENT ON COLUMN HRPO0100A.C_CD IS
'회사코드';

COMMENT ON COLUMN HRPO0100A.EMP_ID IS
'사번';

COMMENT ON COLUMN HRPO0100A.STA_YMD IS
'시작일';

COMMENT ON COLUMN HRPO0100A.SEQ_NO IS
'일련번호';

COMMENT ON COLUMN HRPO0100A.END_YMD IS
'종료일';

COMMENT ON COLUMN HRPO0100A.DOC_NO IS
'문서번호';

COMMENT ON COLUMN HRPO0100A.APPNT_CD IS
'발령코드,/PA02';

COMMENT ON COLUMN HRPO0100A.APPNT_RSN_CD IS
'발령사유코드';

COMMENT ON COLUMN HRPO0100A.STAT_CD IS
'재직상태,/SY02';

COMMENT ON COLUMN HRPO0100A.BIZPL_CD IS
'사업장코드,/SY36';

COMMENT ON COLUMN HRPO0100A.ORG_ID IS
'조직ID';

COMMENT ON COLUMN HRPO0100A.EMP_TYPE IS
'사원유형,/SY01';

COMMENT ON COLUMN HRPO0100A.EMP_GRADE_CD IS
'직급코드,/SY03';

COMMENT ON COLUMN HRPO0100A.SAL_STEP_CD IS
'호봉코드,SY020';

COMMENT ON COLUMN HRPO0100A.DUTY_CD IS
'직책코드,/SY05';

COMMENT ON COLUMN HRPO0100A.JOB_ID IS
'직무ID';

COMMENT ON COLUMN HRPO0100A.POST_CD IS
'직위코드,/SY04';

COMMENT ON COLUMN HRPO0100A.EMP_TITLE_CD IS
'호칭코드,00101';

COMMENT ON COLUMN HRPO0100A.POSITION_ID IS
'포지션ID';

COMMENT ON COLUMN HRPO0100A.DISP_ORG_ID IS
'파견소속ID';

COMMENT ON COLUMN HRPO0100A.DISP_DUTY_CD IS
'파견직책코드';

COMMENT ON COLUMN HRPO0100A.DISP_JOB_ID IS
'파견직무ID';

COMMENT ON COLUMN HRPO0100A.DISP_POSITION_ID IS
'파견포지션ID';

COMMENT ON COLUMN HRPO0100A.OUT_DISP_ASSO_CD IS
'외부파견기관코드';

COMMENT ON COLUMN HRPO0100A.EXPT_PROB_END_YMD IS
'예상수습해제일';

COMMENT ON COLUMN HRPO0100A.EXPT_END_YMD IS
'예상종료일';

COMMENT ON COLUMN HRPO0100A.DUTY_APP_YMD IS
'직책임용일';

COMMENT ON COLUMN HRPO0100A.APP_GRADE IS
'APP_GRADE';

COMMENT ON COLUMN HRPO0100A.LAST_YN IS
'최종여부';

COMMENT ON COLUMN HRPO0100A.SAL_TYPE IS
'연호봉유형,/SY20';

COMMENT ON COLUMN HRPO0100A.APPLY_YMD IS
'적용일';

COMMENT ON COLUMN HRPO0100A.PAY_AREA_CD IS
'급여영역코드,/PY05';

COMMENT ON COLUMN HRPO0100A.ATTEND_AREA_CD IS
'근태영역코드,/TM60';

COMMENT ON COLUMN HRPO0100A.NOTE IS
'비고';

COMMENT ON COLUMN HRPO0100A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN HRPO0100A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN HRPO0100A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN HRPO0100A.MOD_YMDHMS IS
'수정일시';

COMMENT ON COLUMN HRPO0100A.WORK_LOC_ID IS
'발령근무지ID';

COMMENT ON COLUMN HRPO0100A.SCH_END_YMD IS
'조회종료일';

COMMENT ON COLUMN HRPO0100A.STAT_CLASS IS
'재직구분,/SY66';

COMMENT ON COLUMN HRPO0100A.TMP_REST_RSN_CD IS
'휴직사유코드,00232';

COMMENT ON COLUMN HRPO0100A.BTRIP_CLASS IS
'출장구분,GE001';

COMMENT ON COLUMN HRPO0100A.NTNL_CD IS
'국가코드,00060';

COMMENT ON COLUMN HRPO0100A.ROT_WORK_YN IS
'순환보직여부';

COMMENT ON COLUMN HRPO0100A.WORK_LOC_ID_LEG IS
'LEG근무지ID';

COMMENT ON COLUMN HRPO0100A.ORG_ID_LEG IS
'LEG조직ID';

COMMENT ON COLUMN HRPO0100A.HD_COM_CD IS
'관계사코드(전출,전입)';

COMMENT ON COLUMN HRPO0100A.APP_EXEC_YN IS
'발령예외여부(발령일 이후 발령 존재함에도 발령냈을 경우..''Y'')';

COMMENT ON COLUMN HRPO0100A.APP_EXEC_UPDATE_YN IS
'발령예외업데이트여부(확인 후 ''Y''처리)';

COMMENT ON COLUMN HRPO0100A.APP_EXEC_MAIL_YN IS
'예외처리발령 메일발송여부';

COMMENT ON COLUMN HRPO0100A.SEL_STEP_CD IS
'급여연차';

COMMENT ON COLUMN HRPO0100A.ASSIGN_STA_YMD IS
'최초부임일';

CREATE UNIQUE INDEX PK_I_HRPO0100A ON
  HRPO0100A (
    C_CD    ASC,
    EMP_ID  ASC,
    STA_YMD ASC,
    SEQ_NO  ASC );

ALTER TABLE HRPO0100A ADD CONSTRAINT PK_I_HRPO0100A PRIMARY KEY ( C_CD, EMP_ID, STA_YMD, SEQ_NO );

-- CREATE TABLE HRPM0200A 주소
DROP TABLE HRPM0200A CASCADE CONSTRAINTS PURGE;

CREATE TABLE HRPM0200A (
  C_CD           VARCHAR2(20 BYTE) NOT NULL,
  EMP_ID         VARCHAR2(20 BYTE) NOT NULL,
  ADDR_CD        VARCHAR2(20 BYTE) NOT NULL,
  ZIP_NO         VARCHAR2(6 BYTE),
  ADDR           VARCHAR2(500 BYTE),
  DTL_ADDR       VARCHAR2(500 BYTE),
  ENG_ADDR       VARCHAR2(500 BYTE),
  ENG_DTL_ADDR   VARCHAR2(500 BYTE),
  INS_USER_ID    VARCHAR2(20 BYTE),
  INS_YMDHMS     DATE,
  MOD_USER_ID    VARCHAR2(20 BYTE),
  MOD_YMDHMS     DATE
);

COMMENT ON TABLE HRPM0200A IS
'인사기본_주소';

COMMENT ON COLUMN HRPM0200A.C_CD IS
'회사코드';

COMMENT ON COLUMN HRPM0200A.EMP_ID IS
'사번';

COMMENT ON COLUMN HRPM0200A.ADDR_CD IS
'주소코드';

COMMENT ON COLUMN HRPM0200A.ZIP_NO IS
'우편번호';

COMMENT ON COLUMN HRPM0200A.ADDR IS
'동주소';

COMMENT ON COLUMN HRPM0200A.DTL_ADDR IS
'세부주소';

COMMENT ON COLUMN HRPM0200A.ENG_ADDR IS
'영문주소';

COMMENT ON COLUMN HRPM0200A.ENG_DTL_ADDR IS
'영문세부주소';

COMMENT ON COLUMN HRPM0200A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN HRPM0200A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN HRPM0200A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN HRPM0200A.MOD_YMDHMS IS
'수정일시';

CREATE UNIQUE INDEX PK_I_HRPM0200A ON
  HRPM0200A (
    C_CD       ASC,
    EMP_ID     ASC,
    ADDR_CD    ASC
  );

ALTER TABLE HRPM0200A ADD CONSTRAINT PK_I_HRPM0200A PRIMARY KEY ( C_CD, EMP_ID, ADDR_CD );

--CREATE TABLE CMOM0000A 객체관리
DROP TABLE CMOM0000A CASCADE CONSTRAINTS PURGE;

CREATE TABLE CMOM0000A (
  C_CD                  VARCHAR2(20 BYTE) NOT NULL,
  OBJ_TYPE              VARCHAR2(20 BYTE) NOT NULL,
  OBJ_ID                VARCHAR2(20 BYTE) NOT NULL,
  PAR_OBJ_TYPE          VARCHAR2(20 BYTE) NOT NULL,
  PAR_OBJ_ID            VARCHAR2(20 BYTE) NOT NULL,
  STA_YMD               VARCHAR2(8 BYTE) NOT NULL,
  END_YMD               VARCHAR2(8 BYTE),
  SEQ_NO                NUMBER DEFAULT 0 NOT NULL,
  ORDER_NO              NUMBER DEFAULT 0 NOT NULL,
  ETC_PPT_1             VARCHAR2(100 BYTE),
  ETC_PPT_2             VARCHAR2(100 BYTE),
  ETC_PPT_3             VARCHAR2(100 BYTE),
  ETC_PPT_4             VARCHAR2(100 BYTE),
  ETC_PPT_5             VARCHAR2(100 BYTE),
  POS_LV_CD             VARCHAR2(20 BYTE),
  REORG_CLASS           VARCHAR2(20 BYTE),
  REORG_RSN_TXT         VARCHAR2(100 BYTE),
  LEVEL_OF_ASPIRATION   VARCHAR2(20 BYTE),
  REQUIRE_CD            VARCHAR2(20 BYTE),
  INS_USER_ID           VARCHAR2(20 BYTE),
  INS_YMDHMS            DATE,
  MOD_USER_ID           VARCHAR2(20 BYTE),
  MOD_YMDHMS            DATE,
  SUPT_DP_ORDER         NUMBER
);

COMMENT ON TABLE CMOM0000A IS
'(CMOM0000A)객체_관계';

COMMENT ON COLUMN CMOM0000A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMOM0000A.OBJ_TYPE IS
'객체유형';

COMMENT ON COLUMN CMOM0000A.OBJ_ID IS
'객체ID';

COMMENT ON COLUMN CMOM0000A.PAR_OBJ_TYPE IS
'상위객체유형';

COMMENT ON COLUMN CMOM0000A.PAR_OBJ_ID IS
'상위객체ID';

COMMENT ON COLUMN CMOM0000A.STA_YMD IS
'시작일';

COMMENT ON COLUMN CMOM0000A.END_YMD IS
'종료일';

COMMENT ON COLUMN CMOM0000A.SEQ_NO IS
'일련번호';

COMMENT ON COLUMN CMOM0000A.ORDER_NO IS
'정렬순서';

COMMENT ON COLUMN CMOM0000A.ETC_PPT_1 IS
'기타속성1';

COMMENT ON COLUMN CMOM0000A.ETC_PPT_2 IS
'기타속성2';

COMMENT ON COLUMN CMOM0000A.ETC_PPT_3 IS
'기타속성3';

COMMENT ON COLUMN CMOM0000A.ETC_PPT_4 IS
'기타속성4';

COMMENT ON COLUMN CMOM0000A.ETC_PPT_5 IS
'기타속성5';

COMMENT ON COLUMN CMOM0000A.POS_LV_CD IS
'위치레벨코드';

COMMENT ON COLUMN CMOM0000A.REORG_CLASS IS
'개편구분';

COMMENT ON COLUMN CMOM0000A.REORG_RSN_TXT IS
'개편사유내용';

COMMENT ON COLUMN CMOM0000A.LEVEL_OF_ASPIRATION IS
'LEVEL_OF_ASPIRATION';

COMMENT ON COLUMN CMOM0000A.REQUIRE_CD IS
'REQUIRE_CD';

COMMENT ON COLUMN CMOM0000A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMOM0000A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMOM0000A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN CMOM0000A.MOD_YMDHMS IS
'수정일시';

COMMENT ON COLUMN CMOM0000A.SUPT_DP_ORDER IS
'보조정렬순서';

CREATE INDEX IDX_CMOM0000A_01 ON CMOM0000A (
    C_CD        ASC,
    OBJ_ID      ASC,
    OBJ_TYPE    ASC,
    PAR_OBJ_ID  ASC
  );

CREATE INDEX IDX_CMOM0000A_02 ON CMOM0000A (
    C_CD        ASC,
    OBJ_TYPE    ASC,
    OBJ_ID      ASC
  );

CREATE INDEX IDX_CMOM0000A_04 ON CMOM0000A (
    C_CD         ASC,
    PAR_OBJ_TYPE ASC,
    PAR_OBJ_ID   ASC,
    STA_YMD      ASC,
    END_YMD      ASC
  );

CREATE UNIQUE INDEX PK_I_CMOM0000A ON CMOM0000A (
    C_CD          ASC,
    OBJ_TYPE      ASC,
    OBJ_ID        ASC,
    PAR_OBJ_TYPE  ASC,
    PAR_OBJ_ID    ASC,
    STA_YMD       ASC
  );

ALTER TABLE CMOM0000A ADD CONSTRAINT PK_I_CMOM0000A PRIMARY KEY ( C_CD, OBJ_TYPE, OBJ_ID, PAR_OBJ_TYPE, PAR_OBJ_ID, STA_YMD );