-- CREATE CMSY0300A 권한항목
CREATE TABLE CMSY0300A (
  C_CD              VARCHAR2(20 BYTE) NOT NULL,
  PROFILE_ID        VARCHAR2(20 BYTE) NOT NULL,
  PROFILE_NM        VARCHAR2(100 BYTE),
  EXPL              VARCHAR2(100 BYTE),
  GEN_YN            VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (GEN_YN IN ('N','Y')),
  ADM_YN            VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (ADM_YN IN ('N','Y')),
  ALL_OPEN_YN       VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (ALL_OPEN_YN IN ('N','Y')),
  GRP_ALL_SCH_YN    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (GRP_ALL_SCH_YN IN ('N','Y')),
  EMP_SCH_AUTH_CD   VARCHAR2(20 BYTE),
  READ_AUTH_YN      VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (READ_AUTH_YN IN ('N','Y')),
  WRITE_AUTH_YN     VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (WRITE_AUTH_YN IN ('N','Y')),
  PRT_AUTH_YN       VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (PRT_AUTH_YN IN ('N','Y')),
  USE_YN            VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CHECK (USE_YN IN ('N','Y')),
  DP_ORDER          NUMBER DEFAULT 0 NOT NULL,
  PAS_STAT_CD       VARCHAR2(20 BYTE),
  PAS_EMP_TYPE      VARCHAR2(20 BYTE),
  BAS_MODULE_ID     VARCHAR2(20 BYTE),
  BAS_PGM_ID        VARCHAR2(50 BYTE),
  BAS_PGM_NM        VARCHAR2(100 BYTE),
  BAS_LEVEL         VARCHAR2(1 BYTE),
  NOTE              VARCHAR2(500 BYTE),
  PRIV_MASK_YN      VARCHAR2(20 BYTE) DEFAULT 'Y',
  INS_USER_ID       VARCHAR2(20 BYTE),
  INS_YMDHMS        DATE,
  MOD_USER_ID       VARCHAR2(20 BYTE),
  MOD_YMDHMS        DATE
);

COMMENT ON TABLE CMSY0300A IS
'(CMSY0300A)권한_프로파일';

COMMENT ON COLUMN CMSY0300A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMSY0300A.PROFILE_ID IS
'프로파일ID';

COMMENT ON COLUMN CMSY0300A.PROFILE_NM IS
'프로파일명';

COMMENT ON COLUMN CMSY0300A.EXPL IS
'설명';

COMMENT ON COLUMN CMSY0300A.GEN_YN IS
'일반용여부';

COMMENT ON COLUMN CMSY0300A.ADM_YN IS
'담당용여부';

COMMENT ON COLUMN CMSY0300A.ALL_OPEN_YN IS
'전사오픈여부';

COMMENT ON COLUMN CMSY0300A.GRP_ALL_SCH_YN IS
'그룹전체조회여부';

COMMENT ON COLUMN CMSY0300A.EMP_SCH_AUTH_CD IS
'직원조회권한코드';

COMMENT ON COLUMN CMSY0300A.READ_AUTH_YN IS
'읽기권한여부';

COMMENT ON COLUMN CMSY0300A.WRITE_AUTH_YN IS
'쓰기권한여부';

COMMENT ON COLUMN CMSY0300A.PRT_AUTH_YN IS
'출력권한여부';

COMMENT ON COLUMN CMSY0300A.USE_YN IS
'사용여부';

COMMENT ON COLUMN CMSY0300A.DP_ORDER IS
'조회순서';

COMMENT ON COLUMN CMSY0300A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMSY0300A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMSY0300A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN CMSY0300A.MOD_YMDHMS IS
'수정일시';

COMMENT ON COLUMN CMSY0300A.PAS_STAT_CD IS
'인사기본재직상태권한';

COMMENT ON COLUMN CMSY0300A.PAS_EMP_TYPE IS
'인사기본직원구분권한';

COMMENT ON COLUMN CMSY0300A.BAS_MODULE_ID IS
'기본모듈ID(링크용)';

COMMENT ON COLUMN CMSY0300A.BAS_PGM_ID IS
'기본프로그램ID(링크용)';

COMMENT ON COLUMN CMSY0300A.BAS_PGM_NM IS
'기본프로그램명(링크용)';

COMMENT ON COLUMN CMSY0300A.BAS_LEVEL IS
'기본뎁스';

COMMENT ON COLUMN CMSY0300A.NOTE IS
'비고';

COMMENT ON COLUMN CMSY0300A.PRIV_MASK_YN IS
'개인정보 마스킹여부';

CREATE UNIQUE INDEX PK_I_CMSY0300A ON
  CMSY0300A (
    C_CD        ASC,
    PROFILE_ID  ASC
  );

ALTER TABLE CMSY0300A ADD CONSTRAINT PK_I_CMSY0300A PRIMARY KEY ( C_CD, PROFILE_ID );

--CREATE TABLE CMSY0200A 프로그램
CREATE TABLE CMSY0200A (
  C_CD          VARCHAR2(20 BYTE) NOT NULL,
  PGM_ID        VARCHAR2(100 BYTE) NOT NULL,
  PGM_NM        VARCHAR2(200 BYTE),
  URL           VARCHAR2(150 BYTE),
  EXPL          VARCHAR2(200 BYTE),
  USE_YN        VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CHECK (USE_YN IN ('N','Y')),
  HELP_YN       VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (HELP_YN IN ('N','Y')),
  DP_ORDER      NUMBER DEFAULT 0 NOT NULL,
  INS_USER_ID   VARCHAR2(20 BYTE),
  INS_YMDHMS    DATE,
  MOD_USER_ID   VARCHAR2(20 BYTE),
  MOD_YMDHMS    DATE
);

COMMENT ON TABLE CMSY0200A IS
'권한_프로그램';

COMMENT ON COLUMN CMSY0200A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMSY0200A.PGM_ID IS
'프로그램ID';

COMMENT ON COLUMN CMSY0200A.PGM_NM IS
'프로그램명';

COMMENT ON COLUMN CMSY0200A.URL IS
'URL';

COMMENT ON COLUMN CMSY0200A.EXPL IS
'설명';

COMMENT ON COLUMN CMSY0200A.USE_YN IS
'사용여부';

COMMENT ON COLUMN CMSY0200A.HELP_YN IS
'도움말여부';

COMMENT ON COLUMN CMSY0200A.DP_ORDER IS
'조회순서';

COMMENT ON COLUMN CMSY0200A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMSY0200A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMSY0200A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN CMSY0200A.MOD_YMDHMS IS
'수정일시';

CREATE UNIQUE INDEX PK_I_CMSY0200A ON
  CMSY0200A (
    C_CD    ASC,
    PGM_ID  ASC
  );

ALTER TABLE CMSY0200A ADD CONSTRAINT PK_I_CMSY0200A PRIMARY KEY ( C_CD,PGM_ID );

--CREATE TABLE CMSY0301A 모듈
CREATE TABLE CMSY0301A (
  C_CD             VARCHAR2(20 BYTE) NOT NULL,
  MODULE_ID        VARCHAR2(20 BYTE) NOT NULL,
  MODULE_NM        VARCHAR2(100 BYTE),
  ENABL_IMG_URL    VARCHAR2(100 BYTE),
  MAIN_PGM_ID      VARCHAR2(50 BYTE),
  DP_ORDER         NUMBER DEFAULT 0 NOT NULL,
  USE_YN           VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CHECK (USE_YN IN ('N','Y')),
  INS_USER_ID      VARCHAR2(20 BYTE),
  INS_YMDHMS       DATE,
  MOD_USER_ID      VARCHAR2(20 BYTE),
  MOD_YMDHMS       DATE
);

COMMENT ON TABLE CMSY0301A IS
'권한_모듈';

COMMENT ON COLUMN CMSY0301A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMSY0301A.MODULE_ID IS
'모듈ID';

COMMENT ON COLUMN CMSY0301A.MODULE_NM IS
'모듈명';

COMMENT ON COLUMN CMSY0301A.ENABL_IMG_URL IS
'이미지URL';

COMMENT ON COLUMN CMSY0301A.MAIN_PGM_ID IS
'메인프로그램ID';

COMMENT ON COLUMN CMSY0301A.DP_ORDER IS
'조회순서';

COMMENT ON COLUMN CMSY0301A.USE_YN IS
'사용여부';

COMMENT ON COLUMN CMSY0301A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMSY0301A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMSY0301A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN CMSY0301A.MOD_YMDHMS IS
'수정일시';

CREATE UNIQUE INDEX PK_I_CMSY0301A ON
  CMSY0301A (
    C_CD        ASC,
    MODULE_ID   ASC
  );

ALTER TABLE CMSY0301A ADD CONSTRAINT PK_I_CMSY0301A PRIMARY KEY ( C_CD,MODULE_ID );

--CREATE TABLE CMSY0302A 권한메뉴
CREATE TABLE CMSY0302A (
  C_CD              VARCHAR2(20 BYTE) NOT NULL,
  PROFILE_ID        VARCHAR2(20 BYTE) NOT NULL,
  MODULE_ID         VARCHAR2(20 BYTE) NOT NULL,
  MENU_ID           VARCHAR2(20 BYTE) NOT NULL,
  STA_YMD           VARCHAR2(8 BYTE),
  END_YMD           VARCHAR2(8 BYTE),
  MENU_NM           VARCHAR2(100 BYTE),
  MENU_CLASS        VARCHAR2(20 BYTE),
  PGM_ID            VARCHAR2(50 BYTE),
  SQL_ID            VARCHAR2(20 BYTE),
  DP_ORDER          NUMBER DEFAULT 0 NOT NULL,
  EXP_YN            VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (EXP_YN IN ('N','Y')),
  AUTH_APPLY_TYPE   VARCHAR2(20 BYTE),
  EMP_SCH_AUTH_CD   VARCHAR2(20 BYTE),
  READ_AUTH_YN      VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (READ_AUTH_YN IN ('N','Y')),
  WRITE_AUTH_YN     VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (WRITE_AUTH_YN IN ('N','Y')),
  PRT_AUTH_YN       VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (PRT_AUTH_YN IN ('N','Y')),
  PAR_MENU_ID       VARCHAR2(20 BYTE),
  USE_YN            VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CHECK (USE_YN IN ('N','Y')),
  NOTE              VARCHAR2(500 BYTE),
  INS_USER_ID       VARCHAR2(20 BYTE),
  INS_YMDHMS        DATE,
  MOD_USER_ID       VARCHAR2(20 BYTE),
  MOD_YMDHMS        DATE
);

COMMENT ON TABLE CMSY0302A IS
'권한_프로파일_메뉴';

COMMENT ON COLUMN CMSY0302A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMSY0302A.PROFILE_ID IS
'프로파일ID';

COMMENT ON COLUMN CMSY0302A.MODULE_ID IS
'모듈ID';

COMMENT ON COLUMN CMSY0302A.MENU_ID IS
'메뉴ID';

COMMENT ON COLUMN CMSY0302A.STA_YMD IS
'시작일';

COMMENT ON COLUMN CMSY0302A.END_YMD IS
'종료일';

COMMENT ON COLUMN CMSY0302A.MENU_NM IS
'메뉴명';

COMMENT ON COLUMN CMSY0302A.MENU_CLASS IS
'메뉴구분';

COMMENT ON COLUMN CMSY0302A.PGM_ID IS
'프로그램ID';

COMMENT ON COLUMN CMSY0302A.SQL_ID IS
'조건문ID';

COMMENT ON COLUMN CMSY0302A.DP_ORDER IS
'조회순서';

COMMENT ON COLUMN CMSY0302A.EXP_YN IS
'펼쳐보기여부';

COMMENT ON COLUMN CMSY0302A.AUTH_APPLY_TYPE IS
'권한적용유형';

COMMENT ON COLUMN CMSY0302A.EMP_SCH_AUTH_CD IS
'직원조회권한코드';

COMMENT ON COLUMN CMSY0302A.READ_AUTH_YN IS
'읽기권한여부';

COMMENT ON COLUMN CMSY0302A.WRITE_AUTH_YN IS
'쓰기권한여부';

COMMENT ON COLUMN CMSY0302A.PRT_AUTH_YN IS
'출력권한여부';

COMMENT ON COLUMN CMSY0302A.PAR_MENU_ID IS
'상위메뉴ID';

COMMENT ON COLUMN CMSY0302A.USE_YN IS
'사용여부';

COMMENT ON COLUMN CMSY0302A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMSY0302A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMSY0302A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN CMSY0302A.MOD_YMDHMS IS
'수정일시';

COMMENT ON COLUMN CMSY0302A.NOTE IS
'비고';

CREATE UNIQUE INDEX PK_I_CMSY0302A ON
  CMSY0302A (
    C_CD        ASC,
    PROFILE_ID  ASC,
    MODULE_ID   ASC,
    MENU_ID     ASC
  );

ALTER TABLE CMSY0302A ADD CONSTRAINT PK_I_CMSY0302A PRIMARY KEY ( C_CD, PROFILE_ID, MODULE_ID, MENU_ID );

--CREATE TABLE CMSY0303A 권한사용자
CREATE TABLE CMSY0303A (
  C_CD          VARCHAR2(20 BYTE) NOT NULL,
  USER_ID       VARCHAR2(20 BYTE) NOT NULL,
  PROFILE_ID    VARCHAR2(20 BYTE) NOT NULL,
  STA_YMD       VARCHAR2(8 BYTE),
  END_YMD       VARCHAR2(8 BYTE),
  NOTE          VARCHAR2(4000 BYTE),
  INS_USER_ID   VARCHAR2(20 BYTE),
  INS_YMDHMS    DATE,
  MOD_USER_ID   VARCHAR2(20 BYTE),
  MOD_YMDHMS    DATE
);

COMMENT ON TABLE CMSY0303A IS
'권한_프로파일/사용자';

COMMENT ON COLUMN CMSY0303A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMSY0303A.USER_ID IS
'사용자ID';

COMMENT ON COLUMN CMSY0303A.PROFILE_ID IS
'프로파일ID';

COMMENT ON COLUMN CMSY0303A.STA_YMD IS
'시작일';

COMMENT ON COLUMN CMSY0303A.END_YMD IS
'종료일';

COMMENT ON COLUMN CMSY0303A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMSY0303A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMSY0303A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN CMSY0303A.MOD_YMDHMS IS
'수정일시';

COMMENT ON COLUMN CMSY0303A.NOTE IS
'비고';

CREATE UNIQUE INDEX PK_I_CMSY0303A ON
  CMSY0303A (
    C_CD        ASC,
    USER_ID     ASC,
    PROFILE_ID  ASC
  );

--CREATE TABLE CMSY0100A 코드 그룹
CREATE TABLE CMSY0100A (
  C_CD               VARCHAR2(20 BYTE) NOT NULL,
  IDX_CD             VARCHAR2(20 BYTE) NOT NULL,
  IDX_NM             VARCHAR2(100 BYTE),
  DP_ORDER           NUMBER DEFAULT 0 NOT NULL,
  LIMIT_LETTER_CNT   NUMBER DEFAULT 0 NOT NULL,
  MGR_SYS_NM         VARCHAR2(100 BYTE),
  USE_YN             VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CHECK (USE_YN IN ('N','Y')),
  CNVT_CD            VARCHAR2(20 BYTE),
  COND_SEQ_NO1       NUMBER DEFAULT 0,
  COND_SEQ_NO2       NUMBER DEFAULT 0,
  COND_SEQ_NO3       NUMBER DEFAULT 0,
  COND_SEQ_NO4       NUMBER DEFAULT 0,
  COND_SEQ_NO5       NUMBER DEFAULT 0,
  NOTE               VARCHAR2(500 BYTE),
  INS_USER_ID        VARCHAR2(20 BYTE),
  INS_YMDHMS         DATE,
  MOD_YMDHMS         DATE,
  MOD_USER_ID        VARCHAR2(20 BYTE)
);

COMMENT ON TABLE CMSY0100A IS
'코드_인덱스';

COMMENT ON COLUMN CMSY0100A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMSY0100A.IDX_CD IS
'인덱스코드';

COMMENT ON COLUMN CMSY0100A.IDX_NM IS
'인덱스명';

COMMENT ON COLUMN CMSY0100A.DP_ORDER IS
'조회순서';

COMMENT ON COLUMN CMSY0100A.LIMIT_LETTER_CNT IS
'제한글자수';

COMMENT ON COLUMN CMSY0100A.MGR_SYS_NM IS
'주관시스템명';

COMMENT ON COLUMN CMSY0100A.USE_YN IS
'사용여부';

COMMENT ON COLUMN CMSY0100A.CNVT_CD IS
'변환코드';

COMMENT ON COLUMN CMSY0100A.COND_SEQ_NO1 IS
'제약일련번호1';

COMMENT ON COLUMN CMSY0100A.COND_SEQ_NO2 IS
'제약일련번호2';

COMMENT ON COLUMN CMSY0100A.COND_SEQ_NO3 IS
'제약일련번호3';

COMMENT ON COLUMN CMSY0100A.COND_SEQ_NO4 IS
'제약일련번호4';

COMMENT ON COLUMN CMSY0100A.COND_SEQ_NO5 IS
'제약일련번호5';

COMMENT ON COLUMN CMSY0100A.NOTE IS
'비고';

COMMENT ON COLUMN CMSY0100A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMSY0100A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMSY0100A.MOD_YMDHMS IS
'수정일시';

COMMENT ON COLUMN CMSY0100A.MOD_USER_ID IS
'작업자ID';

CREATE UNIQUE INDEX PK_I_CMSY0100A ON
  CMSY0100A (
    C_CD
    ASC,
    IDX_CD
    ASC );

ALTER TABLE CMSY0100A ADD CONSTRAINT PK_I_CMSY0100A PRIMARY KEY ( C_CD, IDX_CD );

--CREATE TABLE CMSY0101A 코드상세
CREATE TABLE CMSY0101A (
  C_CD          VARCHAR2(20 BYTE) NOT NULL,
  IDX_CD        VARCHAR2(20 BYTE) NOT NULL,
  CD            VARCHAR2(20 BYTE) NOT NULL,
  CD_NM         VARCHAR2(200 BYTE),
  DP_ORDER      NUMBER DEFAULT 0 NOT NULL,
  OMIT_CD_NM    VARCHAR2(200 BYTE),
  ENG_NM        VARCHAR2(500 BYTE),
  CNVT_CD       VARCHAR2(20 BYTE),
  STA_YMD       VARCHAR2(8 BYTE),
  END_YMD       VARCHAR2(8 BYTE),
  USE_YN        VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CHECK (USE_YN IN ('N','Y')),
  COND_CD1      VARCHAR2(4000 BYTE),
  COND_CD2      VARCHAR2(4000 BYTE),
  COND_CD3      VARCHAR2(4000 BYTE),
  COND_CD4      VARCHAR2(4000 BYTE),
  COND_CD5      VARCHAR2(4000 BYTE),
  COND_CD6      VARCHAR2(4000 BYTE),
  COND_CD7      VARCHAR2(4000 BYTE),
  COND_CD8      VARCHAR2(4000 BYTE),
  COND_CD9      VARCHAR2(4000 BYTE),
  COND_CD10      VARCHAR2(4000 BYTE),
  COND_STA_CD   VARCHAR2(20 BYTE),
  COND_END_CD   VARCHAR2(20 BYTE),
  DEFAULT_YN    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CHECK (DEFAULT_YN IN ('N','Y')),
  NUM_VAL1      NUMBER DEFAULT 0 NOT NULL,
  NUM_VAL2      NUMBER DEFAULT 0 NOT NULL,
  NUM_VAL3      NUMBER DEFAULT 0 NOT NULL,
  IDX_CD2       VARCHAR2(20 BYTE),
  IMAGE_PATH    VARCHAR2(100 BYTE),
  NOTE          VARCHAR2(500 BYTE),
  INS_USER_ID   VARCHAR2(20 BYTE),
  INS_YMDHMS    DATE,
  MOD_USER_ID   VARCHAR2(20 BYTE),
  MOD_YMDHMS    DATE
);

COMMENT ON TABLE CMSY0101A IS
'(CMSY0101A)코드_공통코드';

COMMENT ON COLUMN CMSY0101A.C_CD IS
'회사코드';

COMMENT ON COLUMN CMSY0101A.IDX_CD IS
'인덱스코드';

COMMENT ON COLUMN CMSY0101A.CD IS
'코드';

COMMENT ON COLUMN CMSY0101A.CD_NM IS
'코드명';

COMMENT ON COLUMN CMSY0101A.DP_ORDER IS
'조회순서';

COMMENT ON COLUMN CMSY0101A.OMIT_CD_NM IS
'약어코드명';

COMMENT ON COLUMN CMSY0101A.ENG_NM IS
'영문명';

COMMENT ON COLUMN CMSY0101A.CNVT_CD IS
'변환코드';

COMMENT ON COLUMN CMSY0101A.STA_YMD IS
'시작일';

COMMENT ON COLUMN CMSY0101A.END_YMD IS
'종료일';

COMMENT ON COLUMN CMSY0101A.USE_YN IS
'사용여부';

COMMENT ON COLUMN CMSY0101A.COND_CD1 IS
'제약코드1';

COMMENT ON COLUMN CMSY0101A.COND_CD2 IS
'제약코드2';

COMMENT ON COLUMN CMSY0101A.COND_CD3 IS
'제약코드3';

COMMENT ON COLUMN CMSY0101A.COND_CD4 IS
'제약코드4';

COMMENT ON COLUMN CMSY0101A.COND_CD5 IS
'제약코드5';

COMMENT ON COLUMN CMSY0101A.COND_CD6 IS
'제약코드6';

COMMENT ON COLUMN CMSY0101A.COND_CD7 IS
'제약코드7';

COMMENT ON COLUMN CMSY0101A.COND_CD8 IS
'제약코드8';

COMMENT ON COLUMN CMSY0101A.COND_CD9 IS
'제약코드9';

COMMENT ON COLUMN CMSY0101A.COND_CD10 IS
'제약코드10';

COMMENT ON COLUMN CMSY0101A.COND_STA_CD IS
'제약시작코드';

COMMENT ON COLUMN CMSY0101A.COND_END_CD IS
'제약종료코드';

COMMENT ON COLUMN CMSY0101A.DEFAULT_YN IS
'디폴트여부';

COMMENT ON COLUMN CMSY0101A.NUM_VAL1 IS
'숫자값1';

COMMENT ON COLUMN CMSY0101A.NUM_VAL2 IS
'숫자값2';

COMMENT ON COLUMN CMSY0101A.NUM_VAL3 IS
'숫자값3';

COMMENT ON COLUMN CMSY0101A.IDX_CD2 IS
'인덱스코드2';

COMMENT ON COLUMN CMSY0101A.IMAGE_PATH IS
'이미지경로';

COMMENT ON COLUMN CMSY0101A.NOTE IS
'비고';

COMMENT ON COLUMN CMSY0101A.INS_USER_ID IS
'입력자ID';

COMMENT ON COLUMN CMSY0101A.INS_YMDHMS IS
'입력일시';

COMMENT ON COLUMN CMSY0101A.MOD_USER_ID IS
'작업자ID';

COMMENT ON COLUMN CMSY0101A.MOD_YMDHMS IS
'수정일시';

CREATE UNIQUE INDEX CMSY0101A_IDX_01 ON
  CMSY0101A (
    CD        ASC,
    IDX_CD    ASC,
    C_CD      ASC,
    CD_NM     ASC
  );

CREATE UNIQUE INDEX CMSY0101A_PK ON
  CMSY0101A (
    C_CD      ASC,
    IDX_CD    ASC,
    CD        ASC
  );

CREATE INDEX CMSY0101A_IDX_02 ON
  CMSY0101A ( IDX_CD ASC );

ALTER TABLE CMSY0101A ADD CONSTRAINT CMSY0101A_PK PRIMARY KEY ( C_CD,IDX_CD,CD );