
CREATE TABLE TSBST0001
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    BBS_SEQ              NUMBER(5) NOT NULL ,
    BBS_NM               VARCHAR2(1500) NULL ,
    BBS_CD               VARCHAR2(10) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSBST0001 IS '게시판기준';

COMMENT ON COLUMN TSBST0001.BBS_NM IS '게시판제목';

COMMENT ON COLUMN TSBST0001.BBS_CD IS '게시판구분';

COMMENT ON COLUMN TSBST0001.C_CD IS '회사코드';

COMMENT ON COLUMN TSBST0001.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSBST0001.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSBST0001.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSBST0001.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSBST0001.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSBST0001.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSBST0001.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSBST0001.NOTE IS '비고';

COMMENT ON COLUMN TSBST0001.BBS_SEQ IS '게시판순번';

CREATE UNIQUE INDEX TSBST0001_PK ON TSBST0001
(C_CD   ASC,BBS_SEQ   ASC);

ALTER TABLE TSBST0001
    ADD CONSTRAINT  TSBST0001_PK PRIMARY KEY (C_CD,BBS_SEQ);

CREATE TABLE TSBST0002
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    SEQ_NO               NUMBER(5) NOT NULL ,
    BBS_SEQ              NUMBER(5) NOT NULL ,
    TYPE_CD              VARCHAR2(10) NULL ,
    FILE_ID              VARCHAR2(10) NULL ,
    TITLE                VARCHAR2(1500) NULL ,
    BBS_TXT              VARCHAR2(4000) NULL ,
    USER_ID              VARCHAR2(15) NULL ,
    HID_YN               VARCHAR2(1) NULL ,
    STA_YMDHMS           VARCHAR2(14) NULL ,
    END_YMDHMS           VARCHAR2(14) NULL ,
    DELETE_YN            VARCHAR2(1) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSBST0002 IS '게시판내용';

COMMENT ON COLUMN TSBST0002.TYPE_CD IS '게시구분';

COMMENT ON COLUMN TSBST0002.TITLE IS '제목';

COMMENT ON COLUMN TSBST0002.C_CD IS '회사코드';

COMMENT ON COLUMN TSBST0002.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSBST0002.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSBST0002.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSBST0002.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSBST0002.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSBST0002.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSBST0002.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSBST0002.USER_ID IS '작성자ID';

COMMENT ON COLUMN TSBST0002.SEQ_NO IS '일련번호';

COMMENT ON COLUMN TSBST0002.STA_YMDHMS IS '시작일시';

COMMENT ON COLUMN TSBST0002.END_YMDHMS IS '종료일시';

COMMENT ON COLUMN TSBST0002.BBS_TXT IS '게시내용';

COMMENT ON COLUMN TSBST0002.DELETE_YN IS '삭제여부';

COMMENT ON COLUMN TSBST0002.HID_YN IS '비밀여부';

COMMENT ON COLUMN TSBST0002.BBS_SEQ IS '게시판순번';

COMMENT ON COLUMN TSBST0002.FILE_ID IS '파일ID';

CREATE UNIQUE INDEX TSBST0002_PK ON TSBST0002
(C_CD   ASC,SEQ_NO   ASC,BBS_SEQ   ASC);

ALTER TABLE TSBST0002
    ADD CONSTRAINT  TSBST0002_PK PRIMARY KEY (C_CD,SEQ_NO,BBS_SEQ);

CREATE TABLE TSBST0003
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    SEQ_NO               NUMBER(5) NOT NULL ,
    BBS_SEQ              NUMBER(5) NOT NULL ,
    COMNT_CD             VARCHAR2(10) NULL ,
    COMNT_TXT            VARCHAR2(1500) NULL ,
    USER_ID              VARCHAR2(15) NULL ,
    HID_YN               VARCHAR2(1) NULL ,
    STA_YMDHMS           VARCHAR2(14) NULL ,
    END_YMDHMS           VARCHAR2(14) NULL ,
    DELETE_YN            VARCHAR2(1) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSBST0003 IS '게시판코멘트';

COMMENT ON COLUMN TSBST0003.COMNT_CD IS '코멘트구분';

COMMENT ON COLUMN TSBST0003.COMNT_TXT IS '코멘트';

COMMENT ON COLUMN TSBST0003.C_CD IS '회사코드';

COMMENT ON COLUMN TSBST0003.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSBST0003.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSBST0003.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSBST0003.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSBST0003.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSBST0003.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSBST0003.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSBST0003.USER_ID IS '작성자ID';

COMMENT ON COLUMN TSBST0003.SEQ_NO IS '일련번호';

COMMENT ON COLUMN TSBST0003.STA_YMDHMS IS '시작일시';

COMMENT ON COLUMN TSBST0003.END_YMDHMS IS '종료일시';

COMMENT ON COLUMN TSBST0003.DELETE_YN IS '삭제여부';

COMMENT ON COLUMN TSBST0003.HID_YN IS '비밀여부';

COMMENT ON COLUMN TSBST0003.BBS_SEQ IS '게시판순번';

CREATE UNIQUE INDEX TSBST0003_PK ON TSBST0003
(C_CD   ASC,SEQ_NO   ASC,BBS_SEQ   ASC);

ALTER TABLE TSBST0003
    ADD CONSTRAINT  TSBST0003_PK PRIMARY KEY (C_CD,SEQ_NO,BBS_SEQ);

CREATE TABLE TSBST0101
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    BBS_SEQ              NUMBER(5) NOT NULL ,
    SEQ_NO               NUMBER(5) NOT NULL ,
    USER_ID              VARCHAR2(15) NULL ,
    STA_YMDHMS           VARCHAR2(14) NULL ,
    END_YMDHMS           VARCHAR2(14) NULL ,
    BBS_AUTH_CD          VARCHAR2(10) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSBST0101 IS '게시판권한';

COMMENT ON COLUMN TSBST0101.SEQ_NO IS '일련번호';

COMMENT ON COLUMN TSBST0101.C_CD IS '회사코드';

COMMENT ON COLUMN TSBST0101.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSBST0101.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSBST0101.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSBST0101.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSBST0101.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSBST0101.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSBST0101.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSBST0101.USER_ID IS '작성자ID';

COMMENT ON COLUMN TSBST0101.BBS_SEQ IS '게시판순번';

COMMENT ON COLUMN TSBST0101.STA_YMDHMS IS '시작일시';

COMMENT ON COLUMN TSBST0101.END_YMDHMS IS '종료일시';

COMMENT ON COLUMN TSBST0101.BBS_AUTH_CD IS '게시판권한코드';

CREATE UNIQUE INDEX TSBST0101_PK ON TSBST0101
(C_CD   ASC,BBS_SEQ   ASC,SEQ_NO   ASC);

ALTER TABLE TSBST0101
    ADD CONSTRAINT  TSBST0101_PK PRIMARY KEY (C_CD,BBS_SEQ,SEQ_NO);

CREATE TABLE TSYAU0001
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    LOGIN_ID             VARCHAR2(15) NOT NULL ,
    USER_ID              VARCHAR2(15) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    USER_NM              VARCHAR2(450) NULL ,
    PASSWORD             VARCHAR2(100) NULL ,
    PWD_U_DATE           DATE NULL ,
    ENABLED              VARCHAR2(1) NULL ,
    LOGIN_DATE           DATE NULL ,
    LOGIN_IP             VARCHAR2(20) NULL ,
    ERR_CNT              NUMBER(1) NULL ,
    SKIN_CD              VARCHAR2(10) NULL ,
    LOCK_YN              VARCHAR2(1) NULL ,
    LOCK_DATE            VARCHAR2(8) NULL ,
    SA_YN                VARCHAR2(1) NULL ,
    USER_CD              VARCHAR2(10) NULL ,
    PROFL_ID             VARCHAR2(10) NULL ,
    MDUL_ID              VARCHAR2(10) NULL ,
    MENU_ID              VARCHAR2(10) NULL ,
    OS_USER_YN           VARCHAR2(1) NULL ,
    OS_ORG_NM            VARCHAR2(450) NULL ,
    OS_COM_NM            VARCHAR2(450) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0001 IS '유저정보';

COMMENT ON COLUMN TSYAU0001.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0001.LOGIN_ID IS '아이디';

COMMENT ON COLUMN TSYAU0001.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYAU0001.END_YMD IS '종료일';

COMMENT ON COLUMN TSYAU0001.USER_NM IS '사용자명';

COMMENT ON COLUMN TSYAU0001.USER_ID IS '사용자ID';

COMMENT ON COLUMN TSYAU0001.PASSWORD IS '비밀번호';

COMMENT ON COLUMN TSYAU0001.PWD_U_DATE IS '비밀번호변경일시';

COMMENT ON COLUMN TSYAU0001.ENABLED IS '계정상태';

COMMENT ON COLUMN TSYAU0001.LOGIN_DATE IS '로그인일시';

COMMENT ON COLUMN TSYAU0001.LOGIN_IP IS '로그인IP';

COMMENT ON COLUMN TSYAU0001.ERR_CNT IS '접속시도횟수';

COMMENT ON COLUMN TSYAU0001.SKIN_CD IS '스킨코드';

COMMENT ON COLUMN TSYAU0001.LOCK_YN IS '휴면여부';

COMMENT ON COLUMN TSYAU0001.LOCK_DATE IS '휴면일시';

COMMENT ON COLUMN TSYAU0001.SA_YN IS '시스템계정_여부';

COMMENT ON COLUMN TSYAU0001.USER_CD IS '사용자유형';

COMMENT ON COLUMN TSYAU0001.PROFL_ID IS '메인_권한ID';

COMMENT ON COLUMN TSYAU0001.MDUL_ID IS '메인_모듈ID';

COMMENT ON COLUMN TSYAU0001.MENU_ID IS '메인_메뉴ID';

COMMENT ON COLUMN TSYAU0001.OS_USER_YN IS '외부유저여부';

COMMENT ON COLUMN TSYAU0001.OS_ORG_NM IS '외부조직명';

COMMENT ON COLUMN TSYAU0001.OS_COM_NM IS '외부회사명';

COMMENT ON COLUMN TSYAU0001.NOTE IS '비고';

COMMENT ON COLUMN TSYAU0001.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0001.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0001.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0001.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0001.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0001.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0001.MOD_TSTZ IS '수정일시_현지';

CREATE UNIQUE INDEX TSYAU0001_PK ON TSYAU0001
(C_CD   ASC,LOGIN_ID   ASC,USER_ID   ASC,STA_YMD   ASC);

ALTER TABLE TSYAU0001
    ADD CONSTRAINT  TSYAU0001_PK PRIMARY KEY (C_CD,LOGIN_ID,USER_ID,STA_YMD);

CREATE TABLE TSYAU0002
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    USER_ID              VARCHAR2(15) NOT NULL ,
    SEQ_NO               NUMBER(5) NOT NULL ,
    ITM_CD               VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    TXT                  VARCHAR2(800) NULL ,
    NOTE                 VARCHAR2(800) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0002 IS '유저참조정보';

COMMENT ON COLUMN TSYAU0002.END_YMD IS '종료일';

COMMENT ON COLUMN TSYAU0002.TXT IS '내용';

COMMENT ON COLUMN TSYAU0002.NOTE IS '비고';

COMMENT ON COLUMN TSYAU0002.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0002.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0002.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0002.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0002.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0002.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0002.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0002.ITM_CD IS '정보유형';

COMMENT ON COLUMN TSYAU0002.SEQ_NO IS '일련번호';

COMMENT ON COLUMN TSYAU0002.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0002.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYAU0002.USER_ID IS '사용자ID';

CREATE UNIQUE INDEX TSYAU0002_PK ON TSYAU0002
(C_CD   ASC,USER_ID   ASC,SEQ_NO   ASC,ITM_CD   ASC,STA_YMD   ASC);

ALTER TABLE TSYAU0002
    ADD CONSTRAINT  TSYAU0002_PK PRIMARY KEY (C_CD,USER_ID,SEQ_NO,ITM_CD,STA_YMD);

CREATE TABLE TSYAU0009
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    LOGIN_ID             VARCHAR2(15) NOT NULL ,
    USER_NM              VARCHAR2(300) NULL ,
    TOKEN                VARCHAR2(100) NULL ,
    LOGIN_DATE           DATE NULL ,
    USER_ID              VARCHAR2(15) NOT NULL 
);

COMMENT ON TABLE TSYAU0009 IS '자동로그인';

COMMENT ON COLUMN TSYAU0009.LOGIN_ID IS '아이디';

COMMENT ON COLUMN TSYAU0009.USER_NM IS '사용자명';

COMMENT ON COLUMN TSYAU0009.TOKEN IS '쿠키 KEY';

COMMENT ON COLUMN TSYAU0009.LOGIN_DATE IS '접속일시';

COMMENT ON COLUMN TSYAU0009.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0009.USER_ID IS '사용자ID';

CREATE UNIQUE INDEX TSYAU0009_PK ON TSYAU0009
(C_CD   ASC,LOGIN_ID   ASC);

ALTER TABLE TSYAU0009
    ADD CONSTRAINT  TSYAU0009_PK PRIMARY KEY (C_CD,LOGIN_ID);

CREATE TABLE TSYAU0101
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    MDUL_ID              VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    MDUL_NM              VARCHAR2(300) NULL ,
    ENG_NM               VARCHAR2(300) NULL ,
    ODR_NO               NUMBER(5) NULL ,
    USE_YN               VARCHAR2(1) NULL ,
    MDUL_CT              VARCHAR2(1500) NULL ,
    MAIN_PGM_ID          VARCHAR2(10) NULL ,
    AUTH_DESC            VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0101 IS '모듈';

COMMENT ON COLUMN TSYAU0101.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYAU0101.END_YMD IS '종료일';

COMMENT ON COLUMN TSYAU0101.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0101.MDUL_ID IS '모듈ID';

COMMENT ON COLUMN TSYAU0101.MDUL_NM IS '모듈명';

COMMENT ON COLUMN TSYAU0101.ENG_NM IS '영어명';

COMMENT ON COLUMN TSYAU0101.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYAU0101.USE_YN IS '사용여부';

COMMENT ON COLUMN TSYAU0101.MDUL_CT IS '모듈컨텐츠';

COMMENT ON COLUMN TSYAU0101.MAIN_PGM_ID IS '메인프로그램ID';

COMMENT ON COLUMN TSYAU0101.AUTH_DESC IS '설명';

COMMENT ON COLUMN TSYAU0101.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0101.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0101.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0101.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0101.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0101.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0101.MOD_TSTZ IS '수정일시_현지';

CREATE UNIQUE INDEX TSYAU0101_PK ON TSYAU0101
(C_CD   ASC,MDUL_ID   ASC,STA_YMD   ASC);

ALTER TABLE TSYAU0101
    ADD CONSTRAINT  TSYAU0101_PK PRIMARY KEY (C_CD,MDUL_ID,STA_YMD);

CREATE TABLE TSYAU0102
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    PGM_ID               VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    PGM_NM               VARCHAR2(450) NULL ,
    ENG_NM               VARCHAR2(450) NULL ,
    PGM_URL              VARCHAR2(800) NULL ,
    ODR_NO               NUMBER(6,2) NULL ,
    USE_YN               VARCHAR2(1) NULL ,
    HLP_YN               VARCHAR2(1) NULL ,
    PGM_DESC             VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0102 IS '프로그램';

COMMENT ON COLUMN TSYAU0102.END_YMD IS '종료일';

COMMENT ON COLUMN TSYAU0102.PGM_ID IS '프로그램ID';

COMMENT ON COLUMN TSYAU0102.PGM_NM IS '프로그램영';

COMMENT ON COLUMN TSYAU0102.ENG_NM IS '영어명';

COMMENT ON COLUMN TSYAU0102.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYAU0102.USE_YN IS '사용여부';

COMMENT ON COLUMN TSYAU0102.PGM_DESC IS '설명';

COMMENT ON COLUMN TSYAU0102.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0102.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0102.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0102.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0102.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0102.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0102.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0102.PGM_URL IS '프로그램URL';

COMMENT ON COLUMN TSYAU0102.HLP_YN IS '도움말여부';

COMMENT ON COLUMN TSYAU0102.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0102.STA_YMD IS '시작일';

CREATE UNIQUE INDEX TSYAU0102_PK ON TSYAU0102
(C_CD   ASC,PGM_ID   ASC,STA_YMD   ASC);

ALTER TABLE TSYAU0102
    ADD CONSTRAINT  TSYAU0102_PK PRIMARY KEY (C_CD,PGM_ID,STA_YMD);

CREATE TABLE TSYAU0104
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    PROFL_ID             VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    AUTH_CD              VARCHAR2(10) NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    PROFL_NM             VARCHAR2(300) NULL ,
    ENG_NM               VARCHAR2(300) NULL ,
    CUD_CD               NUMBER(1) NULL ,
    PRT_CD               NUMBER(1) NULL ,
    USE_YN               VARCHAR2(1) NULL ,
    ODR_NO               NUMBER(5) NULL ,
    ORG_AUTH_CD          VARCHAR2(10) NULL ,
    HR_STAT_CD           VARCHAR2(10) NULL ,
    HR_EMP_TYPE          VARCHAR2(10) NULL ,
    AUTH_DESC            VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0104 IS '권한그룹';

COMMENT ON COLUMN TSYAU0104.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYAU0104.END_YMD IS '종료일';

COMMENT ON COLUMN TSYAU0104.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0104.AUTH_CD IS '권한구분코드';

COMMENT ON COLUMN TSYAU0104.PROFL_NM IS '프로파일명';

COMMENT ON COLUMN TSYAU0104.ENG_NM IS '영어명';

COMMENT ON COLUMN TSYAU0104.PRT_CD IS '출력권한코드';

COMMENT ON COLUMN TSYAU0104.USE_YN IS '사용여부';

COMMENT ON COLUMN TSYAU0104.ORG_AUTH_CD IS '조직권한코드';

COMMENT ON COLUMN TSYAU0104.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0104.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0104.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0104.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0104.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0104.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0104.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0104.CUD_CD IS '권한제어코드';

COMMENT ON COLUMN TSYAU0104.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYAU0104.HR_STAT_CD IS '인사재직상태권한';

COMMENT ON COLUMN TSYAU0104.HR_EMP_TYPE IS '인사직원구분권한';

COMMENT ON COLUMN TSYAU0104.DESC IS '설명';

COMMENT ON COLUMN TSYAU0104.PROFL_ID IS '권한ID';

CREATE UNIQUE INDEX TSYAU0104_PK ON TSYAU0104
(C_CD   ASC,PROFL_ID   ASC,STA_YMD   ASC);

ALTER TABLE TSYAU0104
    ADD CONSTRAINT  TSYAU0104_PK PRIMARY KEY (C_CD,PROFL_ID,STA_YMD);

CREATE TABLE TSYAU0105
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    USER_ID              VARCHAR2(15) NOT NULL ,
    PROFL_ID             VARCHAR2(10) NOT NULL ,
    STA_YMDHMS           VARCHAR2(14) NOT NULL ,
    END_YMDHMS           VARCHAR2(14) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0105 IS '권한사용자';

COMMENT ON COLUMN TSYAU0105.STA_YMDHMS IS '시작일시';

COMMENT ON COLUMN TSYAU0105.END_YMDHMS IS '종료일시';

COMMENT ON COLUMN TSYAU0105.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0105.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0105.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0105.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0105.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0105.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0105.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0105.NOTE IS '비고';

COMMENT ON COLUMN TSYAU0105.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0105.PROFL_ID IS '권한ID';

COMMENT ON COLUMN TSYAU0105.USER_ID IS '사용자ID';

CREATE UNIQUE INDEX TSYAU0105_PK ON TSYAU0105
(C_CD   ASC,USER_ID   ASC,PROFL_ID   ASC,STA_YMDHMS   ASC);

ALTER TABLE TSYAU0105
    ADD CONSTRAINT  TSYAU0105_PK PRIMARY KEY (C_CD,USER_ID,PROFL_ID,STA_YMDHMS);

CREATE TABLE TSYAU0106
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    PROFL_ID             VARCHAR2(10) NOT NULL ,
    AUTH_CD              VARCHAR2(10) NOT NULL ,
    STA_YMDHMS           VARCHAR2(14) NOT NULL ,
    USER_ID              VARCHAR2(15) NOT NULL ,
    END_YMDHMS           VARCHAR2(14) NULL ,
    OP_CD                VARCHAR2(10) NULL ,
    CD_TXT               VARCHAR2(3000) NULL ,
    CD_NM_TXT            VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0106 IS '사용자예외권한';

COMMENT ON COLUMN TSYAU0106.STA_YMDHMS IS '시작일시';

COMMENT ON COLUMN TSYAU0106.END_YMDHMS IS '종료일시';

COMMENT ON COLUMN TSYAU0106.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0106.PROFL_ID IS '권한ID';

COMMENT ON COLUMN TSYAU0106.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0106.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0106.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0106.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0106.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0106.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0106.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0106.AUTH_CD IS '권한구분';

COMMENT ON COLUMN TSYAU0106.OP_CD IS '연산자코드';

COMMENT ON COLUMN TSYAU0106.CD_TXT IS '코드내용';

COMMENT ON COLUMN TSYAU0106.CD_NM_TXT IS '코드명내용';

COMMENT ON COLUMN TSYAU0106.USER_ID IS '사용자ID';

CREATE UNIQUE INDEX TSYAU0106_PK ON TSYAU0106
(C_CD   ASC,PROFL_ID   ASC,AUTH_CD   ASC,STA_YMDHMS   ASC,USER_ID   ASC);

ALTER TABLE TSYAU0106
    ADD CONSTRAINT  TSYAU0106_PK PRIMARY KEY (C_CD,PROFL_ID,AUTH_CD,STA_YMDHMS,USER_ID);

CREATE TABLE TSYAU0107
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    MENU_ID              VARCHAR2(10) NOT NULL ,
    PROFL_ID             VARCHAR2(10) NOT NULL ,
    MDUL_ID              VARCHAR2(10) NOT NULL ,
    STA_YMDHMS           VARCHAR2(14) NOT NULL ,
    END_YMDHMS           VARCHAR2(8) NULL ,
    MENU_NM              VARCHAR2(300) NULL ,
    ENG_NM               VARCHAR2(450) NULL ,
    MENU_TYPE_CD         VARCHAR2(10) NULL ,
    PGM_ID               VARCHAR2(10) NULL ,
    SQL_ID               VARCHAR2(10) NULL ,
    ODR_NO               NUMBER(6,2) NULL ,
    EXP_YN               VARCHAR2(1) NULL ,
    AUTH_TP_CD           VARCHAR2(10) NULL ,
    CUD_CD               NUMBER(1) NULL ,
    PRT_CD               NUMBER(1) NULL ,
    PAR_MENU_ID          VARCHAR2(10) NULL ,
    USE_YN               VARCHAR2(1) NULL ,
    RE_CERT_YN           VARCHAR2(1) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0107 IS '권한별메뉴';

COMMENT ON COLUMN TSYAU0107.STA_YMDHMS IS '시작일시';

COMMENT ON COLUMN TSYAU0107.END_YMDHMS IS '종료일시';

COMMENT ON COLUMN TSYAU0107.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0107.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0107.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0107.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0107.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0107.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0107.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0107.MENU_ID IS '메뉴ID';

COMMENT ON COLUMN TSYAU0107.MENU_NM IS '메뉴영';

COMMENT ON COLUMN TSYAU0107.ENG_NM IS '영어명';

COMMENT ON COLUMN TSYAU0107.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYAU0107.MENU_TYPE_CD IS '메뉴구분';

COMMENT ON COLUMN TSYAU0107.PGM_ID IS '프로그램ID';

COMMENT ON COLUMN TSYAU0107.SQL_ID IS '조건문ID';

COMMENT ON COLUMN TSYAU0107.EXP_YN IS '펼쳐보기여부';

COMMENT ON COLUMN TSYAU0107.AUTH_TP_CD IS '권한적용유형';

COMMENT ON COLUMN TSYAU0107.CUD_CD IS '권한제어코드';

COMMENT ON COLUMN TSYAU0107.PRT_CD IS '출력권한여부';

COMMENT ON COLUMN TSYAU0107.PAR_MENU_ID IS '상위메뉴ID';

COMMENT ON COLUMN TSYAU0107.USE_YN IS '사용여부';

COMMENT ON COLUMN TSYAU0107.RE_CERT_YN IS '재인증여부';

COMMENT ON COLUMN TSYAU0107.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0107.MDUL_ID IS '모듈ID';

COMMENT ON COLUMN TSYAU0107.PROFL_ID IS '권한ID';

CREATE UNIQUE INDEX TSYAU0107_PK ON TSYAU0107
(C_CD   ASC,MENU_ID   ASC,PROFL_ID   ASC,MDUL_ID   ASC,STA_YMDHMS   ASC);

ALTER TABLE TSYAU0107
    ADD CONSTRAINT  TSYAU0107_PK PRIMARY KEY (C_CD,MENU_ID,PROFL_ID,MDUL_ID,STA_YMDHMS);

CREATE TABLE TSYAU0201
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    PGM_ID               VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    TXT                  VARCHAR2(3000) NULL ,
    USE_YN               VARCHAR2(1) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0201 IS '도움말';

COMMENT ON COLUMN TSYAU0201.TXT IS '내용';

COMMENT ON COLUMN TSYAU0201.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0201.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0201.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0201.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0201.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0201.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0201.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0201.PGM_ID IS '프로그램ID';

COMMENT ON COLUMN TSYAU0201.USE_YN IS '사용여부';

COMMENT ON COLUMN TSYAU0201.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0201.STA_YMD IS '시작일';

CREATE UNIQUE INDEX TSYAU0201_PK ON TSYAU0201
(C_CD   ASC,PGM_ID   ASC,STA_YMD   ASC);

ALTER TABLE TSYAU0201
    ADD CONSTRAINT  TSYAU0201_PK PRIMARY KEY (C_CD,PGM_ID,STA_YMD);

CREATE TABLE TSYAU0202
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    LOGIN_ID             VARCHAR2(15) NOT NULL ,
    PROFL_ID             VARCHAR2(10) NOT NULL ,
    MENU_ID              VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    USER_ID              VARCHAR2(15) NOT NULL ,
    ODR_NO               NUMBER(6,2) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYAU0202 IS '마이메뉴';

COMMENT ON COLUMN TSYAU0202.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYAU0202.C_CD IS '회사코드';

COMMENT ON COLUMN TSYAU0202.PROFL_ID IS '권한ID';

COMMENT ON COLUMN TSYAU0202.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYAU0202.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYAU0202.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYAU0202.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYAU0202.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYAU0202.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYAU0202.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYAU0202.MENU_ID IS '메뉴ID';

COMMENT ON COLUMN TSYAU0202.LOGIN_ID IS '아이디';

COMMENT ON COLUMN TSYAU0202.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYAU0202.USER_ID IS '사용자ID';

CREATE UNIQUE INDEX TSYAU0202_PK ON TSYAU0202
(C_CD   ASC,LOGIN_ID   ASC,PROFL_ID   ASC,MENU_ID   ASC,STA_YMD   ASC,USER_ID   ASC);

ALTER TABLE TSYAU0202
    ADD CONSTRAINT  TSYAU0202_PK PRIMARY KEY (C_CD,LOGIN_ID,PROFL_ID,MENU_ID,STA_YMD,USER_ID);

CREATE TABLE TSYFS0001
(
    FILE_ID              VARCHAR2(10) NOT NULL ,
    FILE_CD              VARCHAR2(10) NULL ,
    FILE_PATH            VARCHAR2(300) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYFS0001 IS '파일업로드';

COMMENT ON COLUMN TSYFS0001.FILE_PATH IS '파일경로';

COMMENT ON COLUMN TSYFS0001.FILE_ID IS '파일ID';

COMMENT ON COLUMN TSYFS0001.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYFS0001.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYFS0001.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYFS0001.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYFS0001.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYFS0001.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYFS0001.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYFS0001.FILE_CD IS '파일구분';

CREATE UNIQUE INDEX TSYFS0001_PK ON TSYFS0001
(FILE_ID   ASC);

ALTER TABLE TSYFS0001
    ADD CONSTRAINT  TSYFS0001_PK PRIMARY KEY (FILE_ID);

CREATE TABLE TSYFS0002
(
    FILE_ID              VARCHAR2(10) NOT NULL ,
    SEQ_NO               NUMBER(5) NOT NULL ,
    FILE_NM              VARCHAR2(1500) NULL ,
    SAVE_FILE_NM         VARCHAR2(800) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYFS0002 IS '파일업로드상세';

COMMENT ON COLUMN TSYFS0002.FILE_ID IS '파일ID';

COMMENT ON COLUMN TSYFS0002.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYFS0002.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYFS0002.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYFS0002.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYFS0002.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYFS0002.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYFS0002.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYFS0002.FILE_NM IS '첨부파일명';

COMMENT ON COLUMN TSYFS0002.SEQ_NO IS '일련번호';

COMMENT ON COLUMN TSYFS0002.SAVE_FILE_NM IS '물리파일명';

CREATE UNIQUE INDEX TSYFS0002_PK ON TSYFS0002
(FILE_ID   ASC,SEQ_NO   ASC);

ALTER TABLE TSYFS0002
    ADD CONSTRAINT  TSYFS0002_PK PRIMARY KEY (FILE_ID,SEQ_NO);

CREATE TABLE TSYHS0001
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    LOGIN_ID             VARCHAR2(15) NOT NULL ,
    LOGIN_DATE           DATE NOT NULL ,
    LOGIN_IP             VARCHAR2(15) NULL ,
    ACCESS_CD            VARCHAR2(10) NULL ,
    NOTE                 VARCHAR2(3000) NULL 
);

COMMENT ON TABLE TSYHS0001 IS '로그인이력';

COMMENT ON COLUMN TSYHS0001.LOGIN_DATE IS '접속일시';

COMMENT ON COLUMN TSYHS0001.LOGIN_IP IS '로그인IP';

COMMENT ON COLUMN TSYHS0001.C_CD IS '회사코드';

COMMENT ON COLUMN TSYHS0001.ACCESS_CD IS '접속구분';

COMMENT ON COLUMN TSYHS0001.NOTE IS '비고';

COMMENT ON COLUMN TSYHS0001.LOGIN_ID IS '아이디';

CREATE UNIQUE INDEX TSYHS0001_PK ON TSYHS0001
(C_CD   ASC,LOGIN_ID   ASC,LOGIN_DATE   ASC);

ALTER TABLE TSYHS0001
    ADD CONSTRAINT  TSYHS0001_PK PRIMARY KEY (C_CD,LOGIN_ID,LOGIN_DATE);

CREATE TABLE TSYHS0002
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    LOGIN_ID             VARCHAR2(15) NOT NULL ,
    SEQ_NO               NUMBER(5) NOT NULL ,
    PASSWORD             VARCHAR2(100) NULL ,
    CHG_IP               VARCHAR2(15) NULL ,
    CHG_RSN              VARCHAR2(800) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYHS0002 IS '비밀번호변경이력';

COMMENT ON COLUMN TSYHS0002.SEQ_NO IS '일련번호';

COMMENT ON COLUMN TSYHS0002.CHG_IP IS '변경IP';

COMMENT ON COLUMN TSYHS0002.C_CD IS '회사코드';

COMMENT ON COLUMN TSYHS0002.PASSWORD IS '비밀번호';

COMMENT ON COLUMN TSYHS0002.CHG_RSN IS '변경이유';

COMMENT ON COLUMN TSYHS0002.LOGIN_ID IS '아이디';

COMMENT ON COLUMN TSYHS0002.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYHS0002.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYHS0002.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYHS0002.INS_TSTZ IS '입력일시_현지';

CREATE UNIQUE INDEX TSYHS0002_PK ON TSYHS0002
(C_CD   ASC,LOGIN_ID   ASC,SEQ_NO   ASC);

ALTER TABLE TSYHS0002
    ADD CONSTRAINT  TSYHS0002_PK PRIMARY KEY (C_CD,LOGIN_ID,SEQ_NO);

CREATE TABLE TSYHS0003
(
    C_CD                 VARCHAR2(10) NULL ,
    WK_CD                VARCHAR2(10) NULL ,
    SVC_TYPE             VARCHAR2(10) NULL ,
    PARAM                VARCHAR2(3000) NULL ,
    WK_TXT               VARCHAR2(4000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL 
);

COMMENT ON TABLE TSYHS0003 IS '프로그램작업이력';

COMMENT ON COLUMN TSYHS0003.PARAM IS '파라미터';

COMMENT ON COLUMN TSYHS0003.C_CD IS '회사코드';

COMMENT ON COLUMN TSYHS0003.WK_CD IS '작업구분';

COMMENT ON COLUMN TSYHS0003.WK_TXT IS '작업내용';

COMMENT ON COLUMN TSYHS0003.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYHS0003.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYHS0003.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYHS0003.SVC_TYPE IS '서비스구분';

CREATE TABLE TSYHS0004
(
    C_CD                 VARCHAR2(10) NULL ,
    ERR_CD               VARCHAR2(10) NULL ,
    ERR_TXT              VARCHAR2(4000) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL 
);

COMMENT ON TABLE TSYHS0004 IS '프로그램오류로그';

COMMENT ON COLUMN TSYHS0004.C_CD IS '회사코드';

COMMENT ON COLUMN TSYHS0004.ERR_TXT IS '오류내용';

COMMENT ON COLUMN TSYHS0004.NOTE IS '비고';

COMMENT ON COLUMN TSYHS0004.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYHS0004.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYHS0004.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYHS0004.ERR_CD IS '오류구분';

CREATE TABLE TSYST0001
(
    IDX_ID               VARCHAR2(10) NOT NULL ,
    COM_CD               VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    COM_NM               VARCHAR2(600) NULL ,
    ENG_NM               VARCHAR2(800) NULL ,
    REF_CD_DESC          VARCHAR2(800) NULL ,
    ODR_NO               NUMBER(6,2) NULL ,
    ADD_IDX_CD           VARCHAR2(1500) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0001 IS '공통코드';

COMMENT ON COLUMN TSYST0001.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYST0001.END_YMD IS '종료일';

COMMENT ON COLUMN TSYST0001.IDX_ID IS '인덱스ID';

COMMENT ON COLUMN TSYST0001.COM_CD IS '코드CD';

COMMENT ON COLUMN TSYST0001.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0001.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0001.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0001.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0001.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0001.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0001.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0001.COM_NM IS '코드명';

COMMENT ON COLUMN TSYST0001.ENG_NM IS '영어명';

COMMENT ON COLUMN TSYST0001.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYST0001.REF_CD_DESC IS '코드설명';

COMMENT ON COLUMN TSYST0001.ADD_IDX_CD IS '추가 인덱스ID';

COMMENT ON COLUMN TSYST0001.NOTE IS '비고';

CREATE UNIQUE INDEX TSYST0001_PK ON TSYST0001
(IDX_ID   ASC,COM_CD   ASC,STA_YMD   ASC);

ALTER TABLE TSYST0001
    ADD CONSTRAINT  TSYST0001_PK PRIMARY KEY (IDX_ID,COM_CD,STA_YMD);

CREATE TABLE TSYST0002
(
    IDX_ID               VARCHAR2(10) NOT NULL ,
    REF_CD               VARCHAR2(10) NOT NULL ,
    COM_CD               VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    COND_SEQ_NO          NUMBER(5) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0002 IS '참조코드';

COMMENT ON COLUMN TSYST0002.REF_CD IS '참조CD';

COMMENT ON COLUMN TSYST0002.COND_SEQ_NO IS '제약일련번호';

COMMENT ON COLUMN TSYST0002.COM_CD IS '코드CD';

COMMENT ON COLUMN TSYST0002.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0002.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0002.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0002.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0002.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0002.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0002.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0002.NOTE IS '비고';

COMMENT ON COLUMN TSYST0002.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYST0002.END_YMD IS '종료일';

COMMENT ON COLUMN TSYST0002.IDX_ID IS '인덱스ID';

CREATE UNIQUE INDEX TSYST0002_PK ON TSYST0002
(IDX_ID   ASC,REF_CD   ASC,COM_CD   ASC,STA_YMD   ASC,COND_SEQ_NO   ASC);

ALTER TABLE TSYST0002
    ADD CONSTRAINT  TSYST0002_PK PRIMARY KEY (IDX_ID,REF_CD,COM_CD,STA_YMD,COND_SEQ_NO);

CREATE TABLE TSYST0003
(
    COND_SEQ_NO          NUMBER(5) NOT NULL ,
    IDX_ID               VARCHAR2(10) NOT NULL ,
    COM_CD               VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    REF_CD_DESC          VARCHAR2(3000) NULL ,
    ODR_NO               NUMBER(5) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0003 IS '참조코드제약';

COMMENT ON COLUMN TSYST0003.COND_SEQ_NO IS '제약일련번호';

COMMENT ON COLUMN TSYST0003.IDX_ID IS '인덱스ID';

COMMENT ON COLUMN TSYST0003.COM_CD IS '코드CD';

COMMENT ON COLUMN TSYST0003.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0003.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0003.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0003.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0003.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0003.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0003.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0003.REF_CD_DESC IS '코드설명';

COMMENT ON COLUMN TSYST0003.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYST0003.END_YMD IS '종료일';

COMMENT ON COLUMN TSYST0003.ODR_NO IS '정렬순서';

CREATE UNIQUE INDEX TSYST0003_PK ON TSYST0003
(COND_SEQ_NO   ASC,IDX_ID   ASC,COM_CD   ASC,STA_YMD   ASC);

ALTER TABLE TSYST0003
    ADD CONSTRAINT  TSYST0003_PK PRIMARY KEY (COND_SEQ_NO,IDX_ID,COM_CD,STA_YMD);

CREATE TABLE TSYST0101
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    BIZPL_CD             VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    BIZPL_NM             VARCHAR2(300) NULL ,
    RST_EMP_ID           VARCHAR2(15) NULL ,
    MAIN_YN              VARCHAR2(1) NULL ,
    RST_NM               VARCHAR2(450) NULL ,
    BIZ_NO               VARCHAR2(150) NULL ,
    SINS_BIZPL_CD        VARCHAR2(10) NULL ,
    TAX_OFFI_CD          VARCHAR2(10) NULL ,
    USE_YN               VARCHAR2(1) NULL ,
    LOC_CD               VARCHAR2(10) NULL ,
    ODR_NO               NUMBER(5) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0101 IS '사업장정보';

COMMENT ON COLUMN TSYST0101.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYST0101.END_YMD IS '종료일';

COMMENT ON COLUMN TSYST0101.C_CD IS '회사코드';

COMMENT ON COLUMN TSYST0101.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0101.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0101.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0101.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0101.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0101.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0101.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0101.BIZPL_NM IS '사업장명';

COMMENT ON COLUMN TSYST0101.RST_EMP_ID IS '대표자사번';

COMMENT ON COLUMN TSYST0101.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYST0101.MAIN_YN IS '대표여부';

COMMENT ON COLUMN TSYST0101.BIZPL_CD IS '사업장코드';

COMMENT ON COLUMN TSYST0101.RST_NM IS '대표자성명';

COMMENT ON COLUMN TSYST0101.BIZ_NO IS '사업자등록번호';

COMMENT ON COLUMN TSYST0101.SINS_BIZPL_CD IS '사회보험사업장코드';

COMMENT ON COLUMN TSYST0101.TAX_OFFI_CD IS '세무서코드';

COMMENT ON COLUMN TSYST0101.USE_YN IS '사용여부';

COMMENT ON COLUMN TSYST0101.LOC_CD IS '지역코드';

CREATE UNIQUE INDEX TSYST0101_PK ON TSYST0101
(C_CD   ASC,BIZPL_CD   ASC,STA_YMD   ASC);

ALTER TABLE TSYST0101
    ADD CONSTRAINT  TSYST0101_PK PRIMARY KEY (C_CD,BIZPL_CD,STA_YMD);

CREATE TABLE TSYST0102
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    SYS_VAL_NM           VARCHAR2(450) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    SYS_VAL              VARCHAR2(1500) NULL ,
    MDUL_CD              VARCHAR2(10) NULL ,
    ODR_NO               NUMBER(5) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0102 IS '시스템환경변수';

COMMENT ON COLUMN TSYST0102.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYST0102.END_YMD IS '종료일';

COMMENT ON COLUMN TSYST0102.C_CD IS '회사코드';

COMMENT ON COLUMN TSYST0102.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0102.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0102.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0102.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0102.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0102.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0102.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0102.SYS_VAL IS '환경변수';

COMMENT ON COLUMN TSYST0102.MDUL_CD IS '모듈코드';

COMMENT ON COLUMN TSYST0102.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYST0102.NOTE IS '비고';

COMMENT ON COLUMN TSYST0102.SYS_VAL_NM IS '환경변수명';

CREATE UNIQUE INDEX TSYST0102_PK ON TSYST0102
(C_CD   ASC,SYS_VAL_NM   ASC,STA_YMD   ASC);

ALTER TABLE TSYST0102
    ADD CONSTRAINT  TSYST0102_PK PRIMARY KEY (C_CD,SYS_VAL_NM,STA_YMD);

CREATE TABLE TSYST0103
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    LOGIN_IDLANG_TYPE_CD VARCHAR2(10) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    FIX_CHAR             VARCHAR2(10) NULL ,
    FIX_NO_CNT           NUMBER(1) NULL ,
    USE_YN               VARCHAR2(1) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0103 IS '아이디생성기준';

COMMENT ON COLUMN TSYST0103.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYST0103.END_YMD IS '종료일';

COMMENT ON COLUMN TSYST0103.C_CD IS '회사코드';

COMMENT ON COLUMN TSYST0103.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0103.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0103.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0103.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0103.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0103.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0103.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0103.FIX_CHAR IS '고정값';

COMMENT ON COLUMN TSYST0103.FIX_NO_CNT IS '자동번호자리수';

COMMENT ON COLUMN TSYST0103.USE_YN IS '사용여부';

COMMENT ON COLUMN TSYST0103.NOTE IS '비고';

COMMENT ON COLUMN TSYST0103.LOGIN_IDLANG_TYPE_CD IS '아이디구분코드';

CREATE UNIQUE INDEX TSYST0103_PK ON TSYST0103
(C_CD   ASC,LOGIN_IDLANG_TYPE_CD   ASC,STA_YMD   ASC);

ALTER TABLE TSYST0103
    ADD CONSTRAINT  TSYST0103_PK PRIMARY KEY (C_CD,LOGIN_IDLANG_TYPE_CD,STA_YMD);

CREATE TABLE TSYST0202
(
    LANG_TYPE            VARCHAR2(10) NOT NULL ,
    LANG_TYPE_CD         VARCHAR2(10) NOT NULL ,
    PROPERTY_ID          VARCHAR2(20) NOT NULL ,
    STA_YMD              VARCHAR2(8) NOT NULL ,
    END_YMD              VARCHAR2(8) NULL ,
    TXT                  VARCHAR2(3000) NULL ,
    ODR_NO               NUMBER(5) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0202 IS '언어코드';

COMMENT ON COLUMN TSYST0202.LANG_TYPE IS '언어코드';

COMMENT ON COLUMN TSYST0202.PROPERTY_ID IS '프로퍼티ID';

COMMENT ON COLUMN TSYST0202.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0202.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0202.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0202.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0202.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0202.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0202.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0202.TXT IS '내용';

COMMENT ON COLUMN TSYST0202.STA_YMD IS '시작일';

COMMENT ON COLUMN TSYST0202.END_YMD IS '종료일';

COMMENT ON COLUMN TSYST0202.ODR_NO IS '정렬순서';

COMMENT ON COLUMN TSYST0202.LANG_TYPE_CD IS '구분코드';

CREATE UNIQUE INDEX TSYST0202_PK ON TSYST0202
(LANG_TYPE   ASC,LANG_TYPE_CD   ASC,PROPERTY_ID   ASC,STA_YMD   ASC);

ALTER TABLE TSYST0202
    ADD CONSTRAINT  TSYST0202_PK PRIMARY KEY (LANG_TYPE,LANG_TYPE_CD,PROPERTY_ID,STA_YMD);

CREATE TABLE TSYST0301
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    MAIL_SEQ             NUMBER(5) NOT NULL ,
    MAIL_NM              VARCHAR2(1500) NULL ,
    MAIL_YN              VARCHAR2(1) NULL ,
    ALERT_YN             VARCHAR2(1) NULL ,
    SMS_YN               VARCHAR2(1) NULL ,
    NOTE                 VARCHAR2(3000) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0301 IS '메일발송기준';

COMMENT ON COLUMN TSYST0301.MAIL_NM IS '메일제목';

COMMENT ON COLUMN TSYST0301.MAIL_YN IS '메일여부';

COMMENT ON COLUMN TSYST0301.C_CD IS '회사코드';

COMMENT ON COLUMN TSYST0301.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0301.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0301.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0301.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0301.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0301.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0301.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0301.ALERT_YN IS '알림여부';

COMMENT ON COLUMN TSYST0301.SMS_YN IS 'SMS여부';

COMMENT ON COLUMN TSYST0301.NOTE IS '비고';

COMMENT ON COLUMN TSYST0301.MAIL_SEQ IS '메일순번';

CREATE UNIQUE INDEX TSYST0301_PK ON TSYST0301
(C_CD   ASC,MAIL_SEQ   ASC);

ALTER TABLE TSYST0301
    ADD CONSTRAINT  TSYST0301_PK PRIMARY KEY (C_CD,MAIL_SEQ);

CREATE TABLE TSYST0302
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    MAIL_SEQ             NUMBER(5) NOT NULL ,
    LOGIN_ID             VARCHAR2(15) NOT NULL ,
    TO_USER_ID           VARCHAR2(15) NULL ,
    MAIL_ADDR            VARCHAR2(1500) NULL ,
    ALERT_IP             VARCHAR2(15) NULL ,
    SMS_TEL_NO           VARCHAR2(80) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0302 IS '메일수신대상자';

COMMENT ON COLUMN TSYST0302.LOGIN_ID IS '아이디';

COMMENT ON COLUMN TSYST0302.TO_USER_ID IS '수신자ID';

COMMENT ON COLUMN TSYST0302.C_CD IS '회사코드';

COMMENT ON COLUMN TSYST0302.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0302.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0302.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0302.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0302.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0302.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0302.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0302.MAIL_ADDR IS '메일주소';

COMMENT ON COLUMN TSYST0302.ALERT_IP IS 'IP주소';

COMMENT ON COLUMN TSYST0302.MAIL_SEQ IS '메일순번';

COMMENT ON COLUMN TSYST0302.SMS_TEL_NO IS 'SMS전화번호';

CREATE UNIQUE INDEX TSYST0302_PK ON TSYST0302
(C_CD   ASC,MAIL_SEQ   ASC,LOGIN_ID   ASC);

ALTER TABLE TSYST0302
    ADD CONSTRAINT  TSYST0302_PK PRIMARY KEY (C_CD,MAIL_SEQ,LOGIN_ID);

CREATE TABLE TSYST0303
(
    C_CD                 VARCHAR2(10) NOT NULL ,
    MAIL_SEQ             NUMBER(5) NOT NULL ,
    LOGIN_ID             VARCHAR2(15) NOT NULL ,
    MAIL_CONTENTS        VARCHAR2(4000) NULL ,
    MAIL_TOP_IMG         VARCHAR2(1500) NULL ,
    MAIL_BOM_IMG         VARCHAR2(1500) NULL ,
    ALERT_CONTENTS       VARCHAR2(800) NULL ,
    EMR_YN               VARCHAR2(1) NULL ,
    SEC_YN               VARCHAR2(1) NULL ,
    SMS_CONTENTS         VARCHAR2(800) NULL ,
    OPEN_OBJECT_ID       VARCHAR2(10) NULL ,
    WK_MENU_ID           VARCHAR2(10) NULL ,
    INS_USER_ID          VARCHAR2(15) NULL ,
    INS_DATE             DATE NULL ,
    MOD_USER_ID          VARCHAR2(15) NULL ,
    MOD_DATE             DATE NULL ,
    INS_TSTZ             TIMESTAMP WITH TIME ZONE NULL ,
    MOD_TSTZ             TIMESTAMP WITH TIME ZONE NULL 
);

COMMENT ON TABLE TSYST0303 IS '메일내용';

COMMENT ON COLUMN TSYST0303.LOGIN_ID IS '아이디';

COMMENT ON COLUMN TSYST0303.MAIL_CONTENTS IS '메일내용';

COMMENT ON COLUMN TSYST0303.C_CD IS '회사코드';

COMMENT ON COLUMN TSYST0303.WK_MENU_ID IS '작업메뉴ID';

COMMENT ON COLUMN TSYST0303.INS_USER_ID IS '입력자ID';

COMMENT ON COLUMN TSYST0303.INS_DATE IS '입력일시';

COMMENT ON COLUMN TSYST0303.MOD_USER_ID IS '수정자ID';

COMMENT ON COLUMN TSYST0303.MOD_DATE IS '수정일시';

COMMENT ON COLUMN TSYST0303.INS_TSTZ IS '입력일시_현지';

COMMENT ON COLUMN TSYST0303.MOD_TSTZ IS '수정일시_현지';

COMMENT ON COLUMN TSYST0303.MAIL_TOP_IMG IS '메일상단이미지링크';

COMMENT ON COLUMN TSYST0303.MAIL_BOM_IMG IS '메일하단이미지링크';

COMMENT ON COLUMN TSYST0303.ALERT_CONTENTS IS '알림내용';

COMMENT ON COLUMN TSYST0303.MAIL_SEQ IS '메일순번';

COMMENT ON COLUMN TSYST0303.EMR_YN IS '긴급여부';

COMMENT ON COLUMN TSYST0303.SEC_YN IS '보안여부';

COMMENT ON COLUMN TSYST0303.SMS_CONTENTS IS 'SMS내용';

COMMENT ON COLUMN TSYST0303.OPEN_OBJECT_ID IS '바로가기오브젝트ID';

CREATE UNIQUE INDEX TSYST0303_PK ON TSYST0303
(C_CD   ASC,MAIL_SEQ   ASC,LOGIN_ID   ASC);

ALTER TABLE TSYST0303
    ADD CONSTRAINT  TSYST0303_PK PRIMARY KEY (C_CD,MAIL_SEQ,LOGIN_ID);
